<?php

/**
 * branch list (PC)
 * author : Aruze Gaming America, Inc.
 */
$this->headLink()
        ->prependStylesheet($this->basePath('js/jq/colorbox/colorbox.css'));
$this->headScript()
        ->prependFile($this->basePath('js/jq/colorbox/jquery.colorbox-min.js'));
$title = 'Approval Details';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('app', array(
        'controller' => 'approval',
        'action' => 'details',
        'id'=>$this->id,
)));
$form->prepare();

echo $this->PageCtrl()->getNaviJs();
echo $this->ViewButton()->getViewButtonJs();
?>
<script type="text/javascript">
    $(document).ready(function(){
        var height = $("#approvers_detail").height();
        $('#arrow_down').css("height",height-36);
        $(".attached").colorbox({rel:'group1'});
    });
    function goBack() {
        window.history.back();
    }
    function viewComment(){
        $(".comment img").colorbox();
        console.log('Message');
    }
    function showLoading() {
        $('#load_message').css("display","block");
        $('#load_over').css("display","block");
    }
</script>
<div id="title_bar">
    <h2><?php echo $title; ?></h2>
    <div id="content_arrow_sub"></div>
</div>
<div class="triangle-l"></div>
<ul class="breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>">Top</a></li>
    <li><span onclick="jump('<?php
        echo $this->url('app', array(
                'controller' => 'approval',
                'action' => 'list',
            ));
        ?>');"><?php echo $this->escapeHTML($this->translate('Approval List')); ?></span></li>
    <li><?php echo $this->escapeHTML($this->translate($title)); ?></li>
</ul>
<div class="clear"></div>
<div class="msg_box">
<?php
if ($this->message) :
    echo $this->escapeHTML($this->translate($this->message));
endif;
?>
</div>
<?php
    $jump = "";
    if (1 < $this->ctrlLv) :
        $jump = ' onclick="jump(\''
            . $this->url('app', array(
                'controller' => 'approval',
                'action' => 'export',
                 'id'=>$this->id,
            ))
            . '\');"';
    endif;
?>
<?php if($this->decisionDetails['status'] == 'complete'){?>
    <a class="ctrl link_button<?php
        echo !$jump ? ' disabled' : '';
        ?>"<?php
        echo $jump; ?>><?php
        echo $this->escapeHTML($this->translate('View Document'));
        ?></a>
    <?php } ?> 
    <div class="content_details">
        <div id="application_detail">
            <div class="content_list">
                <div class="row">
                    <div class="row_title">
                        <p>No.</p>
                    </div>
                    <div class="row_details">
                        <p><?php echo $this->decisionDetails['ref_no']?></p>
                    </div>
                </div>
                <div class="row">
                    <div class="row_title">
                        <p>Subject</p>
                    </div>
                    <div class="row_details">
                        <p><?php echo $this->decisionDetails['decision_title']?></p>
                    </div>
                </div>
                <div class="row">
                    <div class="row_title">
                        <p>Applicant</p>
                    </div>
                    <div class="row_details">
                        <p><?php echo $this->decisionDetails['user_name']?></p>
                    </div>
                </div>
                <div class="row">
                    <div class="row_title">
                        <p>Requested Deadline Date</p>
                    </div>
                    <div class="row_details">
                        <p><?php echo $this->decisionDetails['preferred_date']?></p>
                    </div>
                </div>
                <div class="row">
                    <div class="row_title">
                        <p>Request Body</p>
                    </div>
                    <div class="row_details">
                        <p><?php echo $this->decisionDetails['document']?></p>
                    </div>
                </div>
                <div class="row">
                    <div class="row_title">
                        <p>Attachments</p>
                    </div>
                    <div class="row_details">
                    <?php foreach ($this->approvalAttachments as $attachment):?>
                        | <a href="<?php echo $this->url('app', array(
                        'controller' => 'approval',
                        'action' => 'view-file-attachment',
                            'id'=>$attachment['file_no']
                        ))?>" title="<?php echo $attachment['content_type']?>" target="_blank"><?php echo $attachment['file_name']?></a>
                    <?php endforeach;?>			
                    </div>
                </div> 
            </div>
        <div  id="row_route">
            <h3>Route</h3>
            <div class="approvers_row" id="app_row">
                  <div class="approver">User</div>
                  <div class="comment">Comment</div>
                  <div class="last_update">Last Update</div>
                  <div class="status">Status</div>
            </div>
            <div id="feed_wrapper">
                <div id="arrow">
                    <div id="arrow_container">
                        <div id="arrow_down"></div>
                    </div>
                </div>
                <div id="approvers_detail">
                  <div class="approvers_row">
                        <div class="approvers_column"><p title="<?php echo $this->decisionDetails['abbr_name']?>">Applicant</p></div>
                        <div class="approvers_column"><p><?php echo $this->decisionDetails['user_name']?></p></div>
                        <div class="approvers_column comment"><p><?php echo trimLongText(20,$this->decisionDetails['remarks'],$this->decisionDetails['decision_no'],$this->decisionDetails['create_user'], 1)?></p></div>
                        <div class="approvers_column last_update"><p><?php echo $this->decisionDetails['update_time']?></p></div>
                        <div class="approvers_column status"><p><?php if ($this->decisionDetails['status'] == 'receiving' ||$this->decisionDetails['status'] == 'progressing' ||$this->decisionDetails['status'] == 'recalled'){
                            echo 'Applying';}elseif($this->decisionDetails['status'] == 'recalled_by_owner'){ echo 'Owner Recalled';}else echo $this->decisionDetails['status']?></p></div>
                  </div>
                  <?php 
                  foreach ($this->approversList as $approver):?>
                   <div class="approvers_row <?php echo ($approver['active']) ?  "active":""?>">
                      <div class="approvers_column"><p title="<?php echo $approver['position_name']?>"><?php echo $approver['abbr_name']?></p></div>
                      <div class="approvers_column"><p><?php echo $approver['user_name']?></p></div>
                      <div class="approvers_column comment"><p><?php echo trimLongText(20,$approver['remarks'],$this->decisionDetails['decision_no'],$approver['user_no'],0)?></p></div>
                      <div class="approvers_column last_update"><p><?php if(!empty($approver['remarks'])) echo $approver['last_update'];?></p></div>
                      <div class="approvers_column status"><?php  if(($approver['status_no'] == 6)){echo 'Approved';}elseif($approver['status_no'] == 0){echo '';}else echo $approver['status_name'];?></div>
                  </div>
                  <?php  
                  if(($approver['active']) && ($approver['status_no'] == 6) ){$status = 6;}  
                  endforeach;
                  ?>
                </div>
                <div class="clear"></div>
            </div>
        </div>


	<?php echo $this->form()->openTag($form); ?>
        <?php if($this->decisionDetails['status'] == "complete"||$this->decisionDetails['status'] == "rejected"){ ?>
        <div class="back">
            <a href="javascript:window.history.back();">Back</a>
            <!--<input type="submit" name="back" value="Back" onclick="goBack();" />-->
        </div>
        <?php  } elseif(($this->approver && $status)){   ?> 
        <div class="row">
            <div class="row_title">
                <p>Remark</p>
            </div>
            <div class="row_details" id="row_remarks">
                <p><?php echo $this->formElement($form->get('remarks')); ?></p>
                <p><?php echo $this->formElementerrors($form->get('remarks')); ?></p>
            </div>
        </div>
        <div class="row">
            <div></div>
            <div class="row_details">
            <?php echo $this->formSubmit($form->get('recall')) . "\n"; ?>   
        </div>   
        <?php } elseif((!$this->approver && $status == 0) || ($this->user_log == $this->decisionDetails['create_user'])){ ?>
        <div class="row">
            <div class="row_title">
                <p>Remark</p>
            </div>
            <div class="row_details" id="row_remarks">
                <p><?php echo $this->formElement($form->get('remarks')); ?></p>
                <p><?php echo $this->formElementerrors($form->get('remarks')); ?></p>
            </div>
        </div>
        <div class="row">
            <div></div>
            <div class="row_details">
            <?php echo $this->formSubmit($form->get('recall-by-owner')) . "\n"; ?>   
            </div>
        <?php }else{  ?>    
        <div class="row">
            <div class="row_title">
                <p>Remark</p>
            </div>
            <div class="row_details" id="row_remarks">
                <p><?php echo $this->formElement($form->get('remarks')); ?></p>
                <p><?php echo $this->formElementerrors($form->get('remarks')); ?></p>
            </div>
        </div>
        <div class="row">
            <div></div>
            <div class="row_details">
            <?php echo $this->formSubmit($form->get('approve')) . "\n"; ?>
            <?php echo $this->formSubmit($form->get('reject')) . "\n"; ?>
            </div>
        </div>
        <?php }?>
        <?php echo $this->form()->closeTag(); ?>
        </div>
         <div id='load_message' style='display: none;'>Processing, please wait...</div>
        <div id='load_over' style='display: none;'></div>
    </div>
<?php 
function trimLongText($limit=500,$string,$decision_no,$user,$request){
    $string = strip_tags($string);
    
    if (strlen($string) > $limit) {
    
        // truncate string
        $stringCut = substr($string, 0, $limit);
        $controller = '&#39;/approval/read?id='.$decision_no .'&user='.$user .'&#39;';
        $controller2 = '&#39;/approval/read-remarks?id='.$decision_no .'&user='.$user .'&#39;';
        $string = substr($stringCut, 0, strrpos($stringCut, ' ')).'...';
        if($request == 1){
            $string .='<img src="/img/system/read-more.png" title="'.$string.'view more" class="lightbox" onclick="view_button('.$controller.',250, 500, 1);">';
        }else{
            $string .='<img src="/img/system/read-more.png" title="'.$string.'view more" class="lightbox" onclick="view_button('.$controller2.',250, 500, 1);">';
        } 
    }   
    return $string;
}
?> 
