<?php
/**
 * branch progressing (PC)
 * author : Aruze Gaming America, Inc.
 */

$title = 'Approval List - Drafts';
//$title = '?? ??';
$this->headTitle($title);

$form = $this->form;


echo $this->PageCtrl()->getNaviJs();
?>
	<script type="text/javascript">
            $(document).ready(function(){
                $("#search").click(function(){
                        $(".content_form").toggle();
                        $(this).find('i').toggleClass('fa-plus fa-minus');
                });
                $( "#search-key" ).keyup(function() {
                    var val = $("input[type='radio']:checked").val();
                     $('#search-key').attr('name', 'search-'+val);
                  });
                $('input:radio').change(function(){
                    var val = $("input[type='radio']:checked").val();
                     $('#search-key').attr('name', 'search-'+val);
                }
                );        
                $('#apply_date').datepicker({dateFormat: 'yy-mm-dd',
                onSelect: function (selected,inst) {
                var dt = new Date(selected);
                dt.setDate(dt.getDate() + 1);
                $('#apply_date2').val($.datepicker.formatDate(inst.settings.dateFormat, dt));
                $('#apply_date2').datepicker("option", "minDate", dt);
            }}); 
            $('#apply_date2').datepicker({dateFormat: 'yy-mm-dd',
                onSelect: function (selected) {
                var dt = new Date(selected);
                dt.setDate(dt.getDate() - 1);
                $('#apply_date').datepicker("option", "maxDate", dt);
                }
            }); 
            $('#update_time').datepicker({dateFormat: 'yy-mm-dd',
                required: true,
                onSelect: function (selected,inst) {
                var dt = new Date(selected);
                dt.setDate(dt.getDate() + 1);
                $('#update_time2').val($.datepicker.formatDate(inst.settings.dateFormat, dt));
                $('#update_time2').datepicker("option", "minDate", dt);
            }}); 
            $('#update_time2').datepicker({dateFormat: 'yy-mm-dd',
                required: true,
                onSelect: function (selected) {
                var dt = new Date(selected);
                dt.setDate(dt.getDate() - 1);
                $('#update_time').datepicker("option", "maxDate", dt);
                
                }
            }); 
            });
	</script>
<div id="title_bar">
	<h2><?php echo $title; ?></h2>
	<div id="content_arrow_sub"></div>
</div>
<div class="triangle-l"></div>
<ul class="breadcrumb">
	<li><a href="<?php echo BASE_URL; ?>">Top</a></li>
	<li><?php echo $this->escapeHTML($this->translate($title)); ?></li>
</ul>
<div class="clear"></div>
<div class="msg_box">
<?php
if ($this->message) :
	echo $this->escapeHTML($this->translate($this->message));
endif;
?>
</div>
<?php
    $jump = "";
    if (1 < $this->ctrlLv) :
        $jump = ' onclick="jump(\''
            . $this->url('app', array(
                'controller' => 'approval',
                'action' => 'create-draft',
            ))
            . '\');"';
    endif;
?>
        <a class="ctrl link_button<?php
                echo !$jump ? ' disabled' : '';
                ?>"<?php
                echo $jump; ?>><?php
                echo $this->escapeHTML($this->translate('New Application'));
//                echo $this->escapeHTML($this->translate('??'));
            ?></a>
<div class="content_details">
	<div id="approval_menu">
		<ul>
		   <?php 
		    if($this->approver):?>
		    <li><a href="/approval/list">Receiving</a></li>
		    <?php endif;?>
		   <li><a href="/approval/progressing">Progressing</a></li>
		   <li><a href="/approval/complete">Complete</a></li>
		   <li class="active"><a href="#">Draft</a></li>
		</ul>
	</div>
	<a id="search"><i class="fa fa-minus"></i>Search</a>
    <div id="approval_search">
        <?php
        echo $this->form()->openTag($form) . "\n";
        echo $this->formHidden($form->get('ord')) . "\n";
        ?>
        <div class="content_form">
            
            <div class="row">
                    <div class="row_title">
                        <p><?php echo $this->formLabel($form->get('search-decision_title')); ?></p>
                    </div>
                    <div class="row_details">
                        <?php echo $this->formElement($form->get('search-decision_title')); ?>
                        <?php echo $this->formElement($form->get('search-choices')); ?>
                    </div>
            </div>
             <div class="row">
                    <div class="row_title">
                        <p><?php echo $this->formLabel($form->get('search-create_time')); ?></p>
                    </div>
                    <div class="row_details">
                        <?php echo $this->formElement($form->get('search-create_time')); ?><small>~</small><?php echo $this->formElement($form->get('search-create_time2')); ?>
                    </div>
            </div>
            <div class="row">
                <div class="row_title">
                    <p><?php echo $this->formLabel($form->get('search-update_time')); ?></p>
                </div>
                <div class="row_details">
                    <?php echo $this->formElement($form->get('search-update_time')); ?><small>~</small><?php echo $this->formElement($form->get('search-update_time2')); ?>
                </div>
            </div>
            <div class="row">
                <div>

                </div>
                <div class="row_details">
                        <?php echo $this->formElement($form->get('submit')); ?>
                        <?php echo $this->formElement($form->get('clear')); ?>
                </div>
            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
	<div class="content_tab">
		<table>
                    <caption>
                       <?php echo $this->PageCtrl()->getMaxView($this->page); ?>
                    </caption>
			<thead>
                            <tr>
                                <th><?php echo $this->escapeHTML($this->translate('Subject'));
                                    echo $this->PageCtrl()->getOrderLink('document_title'); ?>
                                </th>
                                <th><?php echo $this->escapeHTML($this->translate('Apply Date')); 
                                    echo $this->PageCtrl()->getOrderLink('create_time'); ?> </th>
                                <th><?php echo $this->escapeHTML($this->translate('Last Update'));
                                    echo $this->PageCtrl()->getOrderLink('update_time'); ?></th>
                                <th><?php echo $this->escapeHTML($this->translate('Status'));
                                    echo $this->PageCtrl()->getOrderLink('status'); ?></th>
                                <th><?php echo $this->escapeHTML($this->translate('Delete')); ?></th>
                            </tr>
			</thead>
			<tbody>
                            <?php
                                foreach ($this->rows as $row) {
                            ?>
				<tr>
                                    <td><a href="/approval/create/<?php echo $this->escapeHTML(gv('decision_no', $row)); ?>">
                                        <?php echo $this->escapeHTML(gv('decision_title', $row)); ?></a></td>
                                    <td><?php echo $this->escapeHTML(gv('create_time', $row)); ?></td>
                                    <td><?php echo $this->escapeHTML(gv('update_time', $row)); ?></td>
                                    <td><?php if ($row['status'] == "recalled_by_owner"){?>
                                        recalled
                                        <?php } elseif($row['status'] == "recalled"){echo 'recalled by approver';}else{?>
                                        <?php echo $this->escapeHTML(gv('status', $row)); }?></td>
                                    
                                    <td class="ctrl">
                                        <button type="button" onclick="<?php
                                            echo gv('deleted', $row) ? 'restore' : 'delete';
                                            ?>_btn('<?php
                                            echo gv('decision_no', $row); ?>');" class="ctrl"<?php
                                            echo 4 > $this->ctrlLv ? ' disabled=disabled' : '';
                                            ?>><?php
                                            echo $this->escapeHTML(
                                                    $this->translate((gv('deleted', $row) ? 'Restore' : 'Delete')));
                //                                    $this->translate((gv('deleted', $row) ? '復帰' : '削除')));
                                        ?></button>
                                    </td>
				</tr>
                            <?php
                                }
                            ?>
			</tbody>
		</table>
		 <div id="paginator">
                    <?php echo $this->PageCtrl()->getPagination($this->page); ?>
                    <div class="jump_nav">
                       <?php echo $this->PageCtrl()->getPageJump($this->page); ?>
                    </div>
                    <div class="clear"></div>
		</div>
	</div>
</div>
