<?php

/**
 * branch list (PC)
 * author : Aruze Gaming America, Inc.
 */

$title = 'Approval Details';
//$title = '?? ??';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('app', array(
        'controller' => 'approval',
        'action' => 'details',
        'id'=>$this->id,
)));
$form->prepare();


echo $this->PageCtrl()->getNaviJs();
?>
	<script type="text/javascript">
		$(document).ready(function(){
			var height = $("#approvers_detail").height();
	        $('#arrow_down').css("height",height-33);
		});
	</script>
<div id="title_bar">
	<h2><?php echo $title; ?></h2>
	<div id="content_arrow_sub"></div>
</div>
<div class="triangle-l"></div>
<ul class="breadcrumb">
	<li><a href="<?php echo BASE_URL; ?>">Top</a></li>
	<li><?php echo $this->escapeHTML($this->translate($title)); ?></li>
</ul>
<div class="clear"></div>
<div class="msg_box">
<?php
if ($this->message) :
	echo $this->escapeHTML($this->translate($this->message));
endif;
?>
</div>
<?php
    $jump = "";
    if (1 < $this->ctrlLv) :
        $jump = ' onclick="jump(\''
            . $this->url('app', array(
                'controller' => 'approval',
                'action' => 'export',
                 'id'=>$this->id,
            ))
            . '\');"';
    endif;
?>
        <a class="ctrl link_button<?php
                echo !$jump ? ' disabled' : '';
                ?>"<?php
                echo $jump; ?>><?php
                echo $this->escapeHTML($this->translate('View Document'));
//                echo $this->escapeHTML($this->translate('??'));
            ?></a>
<div class="content_details">
		<div id="application_detail">
			<div class="content_details">
				<div class="content_list">
					<div class="row">
						<div class="row_title">
							<p>No.</p>
						</div>
						<div class="row_details">
							<p><?php echo $this->decisionDetails['ref_no']?></p>
						</div>
					</div>
					<div class="row">
						<div class="row_title">
							Subject
						</div>
						<div class="row_details">
							<p><?php echo $this->decisionDetails['decision_title']?></p>
						</div>
					</div>
					<div class="row">
						<div class="row_title">
							<p>Applicant</p>
						</div>
						<div class="row_details">
							<p><?php echo $this->decisionDetails['user_name']?></p>
						</div>
					</div>
					<div class="row">
						<div class="row_title">
							<p>Requested Deadline Date</p>
						</div>
						<div class="row_details">
							<p><?php echo $this->decisionDetails['preferred_date']?></p>
						</div>
					</div>
					<div class="row">
						<div class="row_title">
							<p>Request Body</p>
						</div>
						<div class="row_details">
							<p><?php echo $this->decisionDetails['document']?></p>
							
							
						</div>
					</div>
					<div class="row">
						<div class="row_title">
							<p>Attachments</p>
						</div>
						<div class="row_details">
						
						 
						
							 <?php foreach ($this->approvalAttachments as $attachment):?>
							 | <a href="<?php echo $this->url('app', array(
                'controller' => 'approval',
                'action' => 'view-file-attachment',
	            'id'=>$attachment['file_no']
            ))?>" title="<?php echo $attachment['content_type']?>"><?php echo $attachment['file_name']?></a>
							
							<?php endforeach;?>
						
						</div>
					</div>
					<div class="rows">
					</div>
				</div>
			
				<div  id="row_route">
          <h3>Route</h3>
          <div class="approvers_row" id="app_row">
                <div class="approver">User</div>
                <div class="comment">Comment</div>
                <div class="last_update">Last Update</div>
                <div class="status">Status</div>
          </div>
            <div id="feed_wrapper">
            <div id="arrow">
              <div id="arrow_container">
               <div id="arrow_down"></div>
              </div>
            </div>
            <div id="approvers_detail">
              <div class="approvers_row">
                  <div class="approvers_column"><p title="<?php echo $this->decisionDetails['abbr_name']?>">Applicant</p></div>
                  <div class="approvers_column"><p><?php echo $this->decisionDetails['user_name']?></p></div>
                  <div class="approvers_column comment"><p><?php echo trimLongText(20,$this->decisionDetails['remarks'])?></p></div>
                  <div class="approvers_column last_update"><p><?php echo $this->decisionDetails['update_time']?></p></div>
                  <div class="approvers_column status">Applying</div>
              </div>
              
              <?php 
              $x = 1;
              foreach ($this->approversList as $approver):?>
               <div class="approvers_row <?php echo ($approver['active']) ?  "active":""?>">
                  <div class="approvers_column"><p title="<?php echo $approver['position_name']?>"><?php echo $approver['abbr_name']?></p></div>
                  <div class="approvers_column"><p><?php echo $approver['user_name']?></p></div>
                  <div class="approvers_column comment"><p><?php echo $approver['remarks']?></p></div>
                  <div class="approvers_column last_update"><p><?php if(!empty($approver['remarks'])) echo $approver['last_update'];?></p></div>
                  <div class="approvers_column status"><?php echo ((int)$approver['status_no']) ? $approver['status_name']:"-" ?></div>
              </div>
              <?php 
              $x++;
              endforeach;?>
              
            </div>
            <div class="clear"></div>
          </div>
        </div>
				 <?php 
                 echo $this->form()->openTag($form);
				 ?>	
					<div class="row">
						<div class="row_title">
							<p>Remark</p>
						</div>
						<div class="row_details" id="row_remarks">
							<p><?php echo $this->formElement($form->get('remarks')); ?></p>
					        <p><?php echo $this->formElementerrors($form->get('remarks')); ?></p>
					
						</div>
					</div>
					<div class="row">
						<div></div>
						<div class="row_details">
						<?php echo $this->formSubmit($form->get('approve')) . "\n"; ?>
						<?php echo $this->formSubmit($form->get('reject')) . "\n"; ?>
						<?php echo $this->formSubmit($form->get('recall')) . "\n"; ?>
						</div>
					</div>
					
				<?php echo $this->form()->closeTag();?>
			</div>
		</div>
		</div>

<?php 

function trimLongText($limit=500,$string){
    $string = strip_tags($string);
    
    if (strlen($string) > $limit) {
    
        // truncate string
        $stringCut = substr($string, 0, $limit);
    
        // make sure it ends in a word so assassinate doesn't become ass...
        $string = substr($stringCut, 0, strrpos($stringCut, ' ')).'... <a href="#" title="'.$string.'"><img src="/img/system/read-more.png"></a>';
    }
    
    return $string;
}
?>