<?php
/**
 * language list (PC)
 * author : Aruze Gaming America, Inc.
 */

$this->headLink()
        ->prependStylesheet($this->basePath('js/jq/colorbox/colorbox.css'));
$this->headScript()
        ->prependFile($this->basePath('js/jq/colorbox/jquery.colorbox-min.js'));

$title = 'Language List';
//$title = '言語 一覧';
$this->headTitle($title);

echo $this->PageCtrl()->getNaviJs();
echo $this->ViewButton()->getViewButtonJs();
?>

<script type="text/javascript">
<!-- //
    function delete_btn(id) {
        if (progress) {
            return false;
        }
        progress = true;
        var url = '<?php
        echo $this->url('app', array(
                    'controller' => 'language',
                    'action' => 'delete',
                ));
        ?>/' + id;

        $.ajax({
            type: 'POST',
            url: url,
            success: function() {
                location.reload();
            }
        });
    }

    function restore_btn(id) {
        if (progress) {
            return false;
        }
        progress = true;
        var url = '<?php
        echo $this->url('app', array(
                    'controller' => 'language',
                    'action' => 'restore',
                ));
        ?>/' + id;

        $.ajax({
            type: 'POST',
            url: url,
            success: function() {
                location.reload();
            }
        });
    }

    function dl_btn(str) {
        $('#translate_file').val(str);
        return $('#dl_form').submit();
    }
// -->
</script>
<div id="title_bar">
	<h2><?php echo $title; ?></h2>
	<div id="content_arrow_sub"></div>
</div>
<form action="<?php
            echo $this->url('app', array(
                'controller' => 'language',
                'action' => 'dl',
                )); ?>" method="post" name="dl_form" id="dl_form">
    <input type="hidden" id="translate_file" name="translate_file" value="">
</form>
<div class="triangle-l"></div>
<ul class="breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>">Top</a></li>
    <li><?php echo $this->escapeHTML($this->translate($title)); ?></li>
</ul>
<div class="clear"></div>
<div id="main">
    <div class="msg_box">
<?php
    if ($this->message) :
        echo $this->escapeHTML($this->translate($this->message));
    endif;
 ?>
    </div>
    <br>

    <div class="right_box">
<?php

    $disabled = 4 > $this->ctrlLv ? true : false;
    $attr = array(
        'url' => $this->url('app', array(
            'controller' => 'language',
            'action' => 'upload-file',
        )),
        'value' => $this->escapeHTML($this->translate('Upload Language File')),
//        'value' => $this->escapeHTML($this->translate('翻訳ファイル Up')),
        'class' => '',
        'height' => 300,
        'width' => 500,
        'frame' => 1,
    );
    echo $this->ViewButton()->printViewButton($attr, $disabled) . "\n";


    $jump = "";
    if (1 < $this->ctrlLv) :
        $jump = ' onclick="jump(\''
            . $this->url('app', array(
                'controller' => 'language',
                'action' => 'add',
            ))
            . '\');"';
    endif;
?>
        <button type="button" class="<?php
                echo !$jump ? ' disabled' : '';
                ?>"<?php
                echo $jump; ?>><?php
                echo $this->escapeHTML($this->translate('Create'));
//                echo $this->escapeHTML($this->translate('新規'));
            ?></button>

    </div>
    <br>

    <!-- list_box -->
    <div class="list_box">
        <table class="list">
            <caption>
                <?php echo $this->PageCtrl()->getNavi($this->page); ?>
            </caption>
            <thead>
                <tr>
                    <th class="ctrl"><?php
                        echo $this->escapeHTML($this->translate('Edit')); ?></th>
                        <!--echo $this->escapeHTML($this->translate('編集')); ?></th>-->

                    <th class="text"><?php
                        echo $this->escapeHTML($this->translate('Name'));
//                        echo $this->escapeHTML($this->translate('言語名'));
                        echo $this->PageCtrl()->getOrderLink('lang_name');
                        ?></th>
                    <th class="name"><?php
                        echo $this->escapeHTML($this->translate('Name (Native)'));
//                        echo $this->escapeHTML($this->translate('言語表記'));
                        echo $this->PageCtrl()->getOrderLink('language');
                        ?></th>
                    <th class="abbr"><?php
                        echo $this->escapeHTML($this->translate('code1'));
//                        echo $this->escapeHTML($this->translate('翻訳1'));
                        echo $this->PageCtrl()->getOrderLink('lang_id');
                        ?></th>
                    <th class="abbr"><?php
                        echo $this->escapeHTML($this->translate('code2'));
//                        echo $this->escapeHTML($this->translate('翻訳2'));
                        echo $this->PageCtrl()->getOrderLink('resource_id');
                        ?></th>
                    <th class="user"><?php
                        echo $this->escapeHTML($this->translate('Create User'));
//                        echo $this->escapeHTML($this->translate('登録者'));
                        echo $this->PageCtrl()->getOrderLink('create_user');
                        ?></th>
                    <th class="date"><?php
                        echo $this->escapeHTML($this->translate('Create Time'));
//                        echo $this->escapeHTML($this->translate('登録日時'));
                        echo $this->PageCtrl()->getOrderLink('create_time');
                        ?></th>
                    <th class="user"><?php
                        echo $this->escapeHTML($this->translate('Update User'));
//                        echo $this->escapeHTML($this->translate('最終更新者'));
                        echo $this->PageCtrl()->getOrderLink('update_user');
                        ?></th>
                    <th class="date"><?php
                        echo $this->escapeHTML($this->translate('Update Time'));
//                        echo $this->escapeHTML($this->translate('最終更新日時'));
                        echo $this->PageCtrl()->getOrderLink('update_time');
                        ?></th>
                    <th class="ctrl"><?php
                        echo $this->escapeHTML($this->translate('Delete')); ?></th>
                        <!--echo $this->escapeHTML($this->translate('削除')); ?></th>-->
                    <th class="ctrl"><?php
                        echo $this->escapeHTML($this->translate('DL')); ?></th>
                </tr>
            </thead>
            <tbody>
<?php
    foreach ($this->rows as $row) {
?>
                <tr<?php echo gv('deleted', $row) ? ' class="deleted"' : ''; ?>>
                    <td class="ctrl">
<?php
    $jump = "";
    if (2 < $this->ctrlLv) :
        $jump = ' onclick="jump(\''
            . $this->url('app', array(
                'controller' => 'language',
                'action' => 'edit',
                'id' => gv('lang_no', $row)
            ))
            . '\');"';
    endif;
?>
                        <button type="button" class="ctrl" <?php
                            echo $jump; ?><?php
                            echo gv('deleted', $row) || !$jump ? ' disabled=disabled' : '';
                            ?>><?php
                            echo $this->escapeHTML($this->translate('Edit'));
//                            echo $this->escapeHTML($this->translate('編集'));
                        ?></button>
                    </td>
                    <td class="text"><?php
                        echo $this->escapeHTML(gv('lang_name', $row)); ?></td>
                    <td class=""><?php
                        echo $this->escapeHTML(gv('language', $row)); ?></td>
                    <td class="name"><?php
                        echo $this->escapeHTML(gv('lang_id', $row)); ?></td>
                    <td class=""><?php
                        echo $this->escapeHTML(gv('resource_id', $row)); ?></td>
                    <td class="user"><?php
                        echo $this->escapeHTML(gv('create_user', $row)); ?></td>
                    <td class="date"><?php
                        echo $this->escapeHTML(gv('create_time', $row)); ?></td>
                    <td class="user"><?php
                        echo $this->escapeHTML(gv('update_user', $row)); ?></td>
                    <td class="date"><?php
                        echo $this->escapeHTML(gv('update_time', $row)); ?></td>

                    <td class="ctrl">
                        <button type="button" onclick="<?php
                            echo gv('deleted', $row) ? 'restore' : 'delete';
                            ?>_btn('<?php
                            echo gv('lang_no', $row); ?>')" class="ctrl"<?php
                            echo 4 > $this->ctrlLv ? ' disabled=disabled' : '';
                            ?>><?php
                            echo $this->escapeHTML(
                                    $this->translate((gv('deleted', $row) ? 'Restore' : 'Delete')));
//                                    $this->translate((gv('deleted', $row) ? '復帰' : '削除')));
                        ?></button>
                    </td>
                    <td class="ctrl">
                        <button type="button" onclick="dl_btn('<?php
                        echo $this->escapeHTML(gv('lang_id', $row)); ?>');" class="ctrl"<?php
                            echo gv('deleted', $row) || 3 > $this->ctrlLv
                                    ? ' disabled=disabled' : '';
                            ?>><?php
                            echo $this->escapeHTML('DL');
                        ?></button>
                    </td>
                </tr>
<?php
    }
?>

            </tbody>
        </table>
    </div>
    <!-- list_box -->

</div>
<br>
        <!-- pc/language/list.phtml -->
