<?php
/**
 * role edit (PC)
 * author : Aruze Gaming America, Inc.
 */

$title = 'Role ' . ($this->action == 'add' ? 'Create' : 'Edit');
//$title = 'ロール ' . ($this->action == 'add' ? '新規登録' : '編集');
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('app', array(
        'controller' => 'role',
        'action' => $this->action,
        'id' => $this->id,
)));
$form->setAttribute('novalidate', 'novalidate');
?>

<script type="text/javascript">
<!-- //
<?php if(!$this->admin): ?>

    $(window).load(function() {
        $('#branch_no option').attr('disabled', true);
        $('#branch_no option:selected').attr('disabled', false);
    });
<?php endif; ?>

    function read_chk_all() {
        if ($("#read_acl_all").prop("checked")) {
            $(".read_acl").prop("checked", true);
        }
        else {
            $(".read_acl").prop("checked", false);
            $(".create_acl").prop("checked", false);
            $(".update_acl").prop("checked", false);
            $(".delete_acl").prop("checked", false);
            $("#create_acl_all").prop("checked", false);
            $("#update_acl_all").prop("checked", false);
            $("#delete_acl_all").prop("checked", false);
        }
    }
    function create_chk_all() {
        if ($("#create_acl_all").prop("checked")) {
            $("#read_acl_all").prop("checked", true);
            $(".read_acl").prop("checked", true);
            $(".create_acl").prop("checked", true);
        }
        else {
            $(".create_acl").prop("checked", false);
            $(".update_acl").prop("checked", false);
            $(".delete_acl").prop("checked", false);
            $("#update_acl_all").prop("checked", false);
            $("#delete_acl_all").prop("checked", false);
        }
    }
    function update_chk_all() {
        if ($("#update_acl_all").prop("checked")) {
            $("#read_acl_all").prop("checked", true);
            $("#create_acl_all").prop("checked", true);
            $(".read_acl").prop("checked", true);
            $(".create_acl").prop("checked", true);
            $(".update_acl").prop("checked", true);
        }
        else {
            $(".update_acl").prop("checked", false);
            $(".delete_acl").prop("checked", false);
            $("#delete_acl_all").prop("checked", false);
        }
    }
    function delete_chk_all() {
        if ($("#delete_acl_all").prop("checked")) {
            $("#read_acl_all").prop("checked", true);
            $("#create_acl_all").prop("checked", true);
            $("#update_acl_all").prop("checked", true);
            $(".read_acl").prop("checked", true);
            $(".create_acl").prop("checked", true);
            $(".update_acl").prop("checked", true);
            $(".delete_acl").prop("checked", true);
        }
        else {
            $(".delete_acl").prop("checked", false);
        }
    }

    function read_chk(no) {
        if (!$("#read_acl_" + no).prop("checked")) {
            $("#create_acl_" + no).prop("checked", false);
            $("#update_acl_" + no).prop("checked", false);
            $("#delete_acl_" + no).prop("checked", false);
        }
        return;
    }
    function create_chk(no) {
        if ($("#create_acl_" + no).prop("checked")) {
            $("#read_acl_" + no).prop("checked", true);
        }
        else {
            $("#update_acl_" + no).prop("checked", false);
            $("#delete_acl_" + no).prop("checked", false);
        }
    }
    function update_chk(no) {
        if ($("#update_acl_" + no).prop("checked")) {
            $("#read_acl_" + no).prop("checked", true);
            $("#create_acl_" + no).prop("checked", true);
        }
        else {
            $("#delete_acl_" + no).prop("checked", false);
        }
    }
    function delete_chk(no) {
        if ($("#delete_acl_" + no).prop("checked")) {
            $("#read_acl_" + no).prop("checked", true);
            $("#create_acl_" + no).prop("checked", true);
            $("#update_acl_" + no).prop("checked", true);
        }
    }

    $(function() {
        $('#user_no').resizable({
            minHeight: 100,
            minWidth:  100,
            maxWidth:  200
        });

<?php if ($this->admin): ?>

        $('#branch_no').change(function() {
            var branch_no = $('#branch_no').val();
            var url = '<?php
                echo $this->url('app', array(
                    'controller' => 'section',
                    'action' => 'get-select',
                )); ?>';
            var data = 'branch_no=' + branch_no + '&type=edit';

            $.ajax({
                type: 'POST',
                url: url,
                data: data,
                success: function(res) {
                    $('#select_user_top').html(res);
                    $('#user_no').empty();
                    $('#user_selector').empty();
                }
            });
        });
<?php endif; ?>

    });

    $(document).ready(function() {
        if (progress) {
            return false;
        }

        $('#user_add_btn').click(function() {
            move('user_selector', 'user_no');
        });

        $('#user_del_btn').click(function() {
            move('user_no', 'user_selector');
        });

        var move = function(_this, target) {
            $('#' + _this + ' option:selected').each(function() {
                $('#' + target).append($(this).clone());
                $(this).remove();
            });
        };
    });

    $(document).on('change', '#section_no', function() {
        var branch_no = $('#branch_no').val();
        if (!branch_no) {
            return false;
        }

        var section_no = $('#section_no').val();
        if (!section_no) {
            $('#user_selector').empty();
            return false;
        }

        var not_user = '';
        $('#user_no option').each(function() {
            not_user += '&not_user[]=' + $(this).val();
        });

        var url = '<?php
            echo $this->url('app', array(
                'controller' => 'user',
                'action' => 'get-user-section',
            )); ?>';
        var data = 'branch_no=' + branch_no
                + '&section_no=' + section_no
                + not_user;

        $.ajax({
            type: 'POST',
            url: url,
            data: data,
            success: function(res) {
                $('#select_user_right').html(res);

                $('#user_selector').resizable({
                    minHeight: 100,
                    minWidth:  100,
                    maxWidth:  200
                });
            }
        });
    });

    $(document).ready(function() {
        $('#submit').click(function() {
            if (progress) {
                return false;
            }
            else {
                $('#user_no option').each(function() {
                    $(this).prop("selected", true);
                });

                progress = true;
                return $('#role_edit').submit();
            }
        });
    });
// -->
</script>
<div id="title_bar">
	<h2><?php echo $title; ?></h2>
	<div id="content_arrow_sub"></div>
</div>
<div class="triangle-l"></div>
<ul class="breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>">Top</a></li>
    <li><span onclick="jump('<?php
            echo $this->url('app', array(
                    'controller' => 'role',
                    'action' => 'list',
                ));
            ?>');"><?php
            echo $this->escapeHTML($this->translate('Role List')); ?></span></li>
            <!--echo $this->escapeHTML($this->translate('ロール 一覧')); ?></span></li>-->
    <li><?php echo $this->escapeHTML($this->translate($title)); ?></li>
</ul>
<div class="clear"></div>
<div id="main">
    <div class="err_msg"><?php
    if (isset($this->err_msg) && $this->err_msg) :
        echo "<br><br>";
        echo nl2br(
            $this->escapeHtml($this->translate($this->err_msg)), false);
    endif; ?></div>

    <div class="form_tpl">
<?php
    echo $this->form()->openTag($form) . "\n";
    echo $this->formHidden($form->get('token_id')) . "\n";
    echo $this->formHidden($form->get('role_no')) . "\n";
    echo $this->formHidden($form->get('update_time')) . "\n";

    $error = $this->formElementerrors($form->get('token_id'));
    if ($error) :
        echo $error . "\n";
    endif;

    echo $this->formHidden($form->get('before_branch_no')) . "\n";
    echo $this->formHidden($form->get('before_role_name')) . "\n";

    if (isset($this->beforeData)) :
        $before_user = gv('before_user_no', $this->beforeData);
        $before_level = gv('before_level', $this->beforeData);

        if ($before_user) :
            foreach ($before_user as $row) { ?>

    <input type="hidden" name="before_user_no[]" value="<?php echo (int) $row; ?>"><?php
            }
        endif;

        if ($before_level) :
            foreach ($before_level as $ctrl => $lv) { ?>

    <input type="hidden" name="before_level[<?php  echo (int) $ctrl;
        ?>]" value="<?php echo (int) $lv; ?>"><?php
            }
        endif;

    endif;

?>

    <div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('branch_no')); ?>
			<span class="required">*</span>
           </div>
		<div class="row_details">
			<?php echo $this->formElement($form->get('branch_no')); ?><br>
			<?php echo $this->formElementerrors($form->get('branch_no')); ?>
          </div>
	</div>
	<div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('role_name')); ?>
			<span class="required">*</span>
           </div>
		<div class="row_details">
			<?php echo $this->formElement($form->get('role_name')); ?><br>
			<?php echo $this->formElementerrors($form->get('role_name')); ?>
        </div>
	</div>
	<div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('user_no')); ?>
			<span class="required">*</span>
	   </div>
		<div class="row_details">
			<div id="role_user">
				<div id="select_user_top">
					<?php echo $this->formElement($form->get('section_no')); ?>
				</div>

				<div id="select_user_left">
					<?php echo $this->formElement($form->get('user_no')); ?>
				</div>
				<div class="button_controller">
				<div id="select_user_center">
					<button type="button" id="user_add_btn"><?php
							echo $this->escapeHTML($this->translate('Add'));
	//                            echo $this->escapeHTML($this->translate('追加'));
						?></button>
					<br>
					<br>
					<button type="button" id="user_del_btn"><?php
							echo $this->escapeHTML($this->translate('Remove'));
	//                            echo $this->escapeHTML($this->translate('削除'));
						?></button>
					<br>
					<br>
				</div>
				</div>
				<div id="select_user_right">
					<?php echo $this->formElement($form->get('user_selector')); ?>
				</div>
				<br class="float_c">
				<?php echo $this->formElementerrors($form->get('user_no')); ?>
			</div>
		</div>
	</div>
	
	 <div class="row">
		<div class="row_title">
   
			<caption class="left">
				<?php
					echo $this->escapeHTML($this->translate('Setting Authority')) . "<br>\n";
	//                echo $this->escapeHTML($this->translate('権限設定')) . "<br>\n";?>
			</caption>
		</div>
		<div class="row_details">
			<?php echo $this->formElementerrors($form->get('level'));?>
			<table class="list">
			<thead>
				<tr>
					<th class="name"><?php
						echo $this->escapeHTML($this->translate('Controller')); ?></th>
						<!--echo $this->escapeHTML($this->translate('コントローラ')); ?></th>-->
					<th class="chk">
						<?php
						echo $this->escapeHTML($this->translate('View')); ?>
						<!--echo $this->escapeHTML($this->translate('閲覧')); ?>-->

						<input type="checkbox" id="read_acl_all" name="read_acl_all" value="1" onclick="read_chk_all();">
					</th>
					<th class="chk">
						<?php
						echo $this->escapeHTML($this->translate('Create')); ?>
						<!--echo $this->escapeHTML($this->translate('登録')); ?>-->

						<input type="checkbox" id="create_acl_all" name="create_acl_all" value="1" onclick="create_chk_all();">
					</th>
					<th class="chk">
						<?php
						echo $this->escapeHTML($this->translate('Update')); ?>
						<!--echo $this->escapeHTML($this->translate('更新')); ?>-->

						<input type="checkbox" id="update_acl_all" name="update_acl_all" value="1" onclick="update_chk_all();">
					</th>
					<th class="chk">
						<?php
						echo $this->escapeHTML($this->translate('Delete')); ?>
						<!--echo $this->escapeHTML($this->translate('削除')); ?>-->

						<input type="checkbox" id="delete_acl_all" name="delete_acl_all" value="1" onclick="delete_chk_all();">
					</th>
				</tr>
			</thead>
			<tbody>

	<?php
		foreach ($this->ctrlList as $row) {
			$ctrl_no = (int) gv('controller_no', $row);

			if ($this->form_level) :
				$r_checked = 0 < gv($ctrl_no, $this->form_level) ? ' checked' : '';
				$c_checked = 1 < gv($ctrl_no, $this->form_level) ? ' checked' : '';
				$u_checked = 2 < gv($ctrl_no, $this->form_level) ? ' checked' : '';
				$d_checked = 3 < gv($ctrl_no, $this->form_level) ? ' checked' : '';

			else :
				$r_checked = 0 < gv('level', $row) ? ' checked' : '';
				$c_checked = 1 < gv('level', $row) ? ' checked' : '';
				$u_checked = 2 < gv('level', $row) ? ' checked' : '';
				$d_checked = 3 < gv('level', $row) ? ' checked' : '';

			endif;

			?>
				<tr>
					<td class="tooltip" title="<?php
						echo gv('ctrl_description', $row)
								? $this->escapeHTML($this->translate(gv('ctrl_description', $row)))
								: "";
					?>"><?php echo $this->escapeHTML(gv('controller_name', $row)); ?></td>
					<td class="chk">
						<input type="checkbox" class="read_acl" id="read_acl_<?php
							echo $ctrl_no; ?>" name="level[<?php
							echo $ctrl_no; ?>]"<?php
							echo $r_checked;
							?> value="1" onclick="read_chk(<?php
							echo $ctrl_no; ?>)">
					</td>
					<td class="chk">
						<input type="checkbox" class="create_acl" id="create_acl_<?php
							echo $ctrl_no; ?>" name="level[<?php
							echo $ctrl_no; ?>]"<?php
							echo $c_checked;
							?> value="2" onclick="create_chk(<?php
							echo $ctrl_no; ?>)">
					</td>
					<td class="chk">
						<input type="checkbox" class="update_acl" id="update_acl_<?php
							echo $ctrl_no; ?>" name="level[<?php
							echo $ctrl_no; ?>]"<?php
							echo $u_checked;
							?> value="3" onclick="update_chk(<?php
							echo $ctrl_no; ?>)">
					</td>
					<td class="chk">
						<input type="checkbox" class="delete_acl" id="delete_acl_<?php
							echo $ctrl_no; ?>" name="level[<?php
							echo $ctrl_no; ?>]"<?php
							echo $d_checked;
							?> value="4" onclick="delete_chk(<?php
							echo $ctrl_no; ?>)">
					</td>
				</tr>
	<?php
		}
	?>

			</tbody>
			</table>
		</div>
	</div>

	<div class="row">
		<div></div>
		<div class="row_details">
	<?php
		echo $this->formSubmit($form->get('submit')) . "\n";
		echo $this->formReset($form->get('reset')) . "\n";
		echo $this->form()->closeTag();
	?>
		</div>
	</div>
</div>
</div>
<br>

        <!-- pc/role/edit.phtml -->
