<?php
/**
 * status edit (PC)
 * author : Aruze Gaming America, Inc.
 */

$title = 'Status ' . ($this->action == 'add' ? 'Create' : 'Edit');
//$title = 'ステータス ' . ($this->action == 'add' ? '新規登録' : '編集');
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('app', array(
        'controller' => 'status',
        'action' => $this->action,
        'id' => $this->id,
)));
$form->setAttribute('novalidate', 'novalidate');
?>
<div id="title_bar">
	<h2><?php echo $title; ?></h2>
	<div id="content_arrow_sub"></div>
</div>
<div class="triangle-l"></div>
<ul class="breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>">Top</a></li>
    <li><span onclick="jump('<?php
            echo $this->url('app', array(
                    'controller' => 'status',
                    'action' => 'list',
                ));
            ?>');"><?php
                echo $this->escapeHTML($this->translate('Status List')); ?></span></li>
                <!--echo $this->escapeHTML($this->translate('ステータス 一覧')); ?></span></li>-->
    <li><?php echo $this->escapeHTML($this->translate($title)); ?></li>
</ul>
<div class="clear"></div>
<div id="main">
    <div class="err_msg"><?php
    if (isset($this->err_msg) && $this->err_msg) :
        echo "<br><br>";
        echo nl2br(
            $this->escapeHtml($this->translate($this->err_msg)), false);
    endif; ?></div>

    <div class="form_center">
<?php
    echo $this->form()->openTag($form) . "\n";
    echo $this->formHidden($form->get('token_id')) . "\n";
    echo $this->formHidden($form->get('status_no')) . "\n";
    echo $this->formHidden($form->get('update_time')) . "\n";

    $error = $this->formElementerrors($form->get('token_id'));
    if ($error) :
        echo $error . "\n";
    endif;

    echo $this->formHidden($form->get('before_status_name')) . "\n";
    echo $this->formHidden($form->get('before_stat_description')) . "\n";
    echo $this->formHidden($form->get('before_locked')) . "\n";
?>

   <div class="row">
		<div class="row_title">
                <?php echo $this->formLabel($form->get('status_name')); ?>
                <span class="required">*</span>
            </div>
		<div class="row_details">
                <?php echo $this->formElement($form->get('status_name')); ?><br>
                <?php echo $this->formElementerrors($form->get('status_name')); ?>
          </div>
	</div>
	<div class="row">
		<div class="row_title">
                <?php echo $this->formLabel($form->get('stat_description')); ?>
		</div>
		<div class="row_details">
			<?php echo $this->formElement($form->get('stat_description')); ?><br>
			<?php echo $this->formElementerrors($form->get('stat_description')); ?>
		</div>
	</div>
	<div class="row">
		<div class="row_title">
                <?php echo $this->formLabel($form->get('locked')); ?>
                <span class="required">*</span>
        </div>
		<div class="row_details">
                <?php echo $this->formElement($form->get('locked')); ?><br>
                <?php echo $this->formElementerrors($form->get('locked')); ?>
          </div>
	</div>
	<div class="row">
		<div></div>
		<div class="row_details">
	<?php
		echo $this->formSubmit($form->get('submit')) . "\n";
		echo $this->formReset($form->get('reset')) . "\n";
		echo $this->form()->closeTag();
	?>
		</div>
	</div>
</div>
</div>
<br>

<script type="text/javascript">
<!-- //
    $(document).ready(function() {
        $('#submit').click(function() {
            if (progress) {
                return false;
            }
            else {
                progress = true;
                return $('#status_edit').submit();
            }
        });
    });
// -->
</script>

        <!-- pc/status/edit.phtml -->
