<?php
/**
 * page edit (PC)
 * author : Aruze Gaming America, Inc.
 */

$title = 'ページ ' . ($this->action == 'add' ? 'Create' : 'Edit');
//$title = 'ページ ' . ($this->action == 'add' ? '新規登録' : '編集');
$this->headTitle($title);

$this->headLink()
        ->prependStylesheet($this->basePath('js/jq/colorbox/colorbox.css'));
$this->headScript()
        ->prependFile($this->basePath('js/jq/colorbox/jquery.colorbox-min.js'));

$form = $this->form;
$form->setAttribute('action', $this->url('app', array(
        'controller' => 'page',
        'action' => $this->action,
        'id' => $this->id,
)));
$form->setAttribute('novalidate', 'novalidate');

echo $this->ViewButton()->getViewButtonJs();
?>

<script type="text/javascript">
<!-- //
    function select_image(file) {
        if (!file) {
            return;
        }
        $('#icon').val(file);
        $.colorbox.close();
        return;
    }
// -->
</script>
<div id="title_bar">
	<h2><?php echo $title; ?></h2>
	<div id="content_arrow_sub"></div>
</div>
<div class="triangle-l"></div>
<ul class="breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>">Top</a></li>
    <li><span onclick="jump('<?php
            echo $this->url('app', array(
                    'controller' => 'page',
                    'action' => 'list',
                ));
            ?>');"><?php
                echo $this->escapeHTML($this->translate('Page List')); ?></span></li>
                <!--echo $this->escapeHTML($this->translate('ページ 一覧')); ?></span></li>-->
    <li><?php echo $this->escapeHTML($this->translate($title)); ?></li>
</ul>
<div class="clear"></div>
<div id="main">
    <div class="err_msg"><?php
    if (isset($this->err_msg) && $this->err_msg) :
        echo "<br><br>";
        echo nl2br(
            $this->escapeHtml($this->translate($this->err_msg)), false);
    endif; ?></div>

    <br>
	<div class="form_center">
<?php
    echo $this->form()->openTag($form) . "\n";
    echo $this->formHidden($form->get('token_id')) . "\n";
    echo $this->formHidden($form->get('page_no')) . "\n";
    echo $this->formHidden($form->get('update_time')) . "\n";

    $error = $this->formElementerrors($form->get('token_id'));
    if ($error) :
        echo $error . "\n";
    endif;

    echo $this->formHidden($form->get('before_category_no')) . "\n";
    echo $this->formHidden($form->get('before_controller_no')) . "\n";
    echo $this->formHidden($form->get('before_page_title')) . "\n";
    echo $this->formHidden($form->get('before_page_uri')) . "\n";
    echo $this->formHidden($form->get('before_page_description')) . "\n";
    echo $this->formHidden($form->get('before_icon')) . "\n";
    echo $this->formHidden($form->get('before_use_mobile')) . "\n";

?>

    <div class="row">
			<div class="row_title">
                <?php echo $this->formLabel($form->get('category_no')); ?>
                <span class="required">*</span>
            </div>
			<div class="row_details">
                <?php echo $this->formElement($form->get('category_no')); ?><br>
                <?php echo $this->formElementerrors($form->get('category_no')); ?>
          	</div>
		</div>
		<div class="row">
			<div class="row_title">
                <?php echo $this->formLabel($form->get('controller_no')); ?>
                <span class="required">*</span>
            </div>
			<div class="row_details">
                <?php echo $this->formElement($form->get('controller_no')); ?><br>
                <?php echo $this->formElementerrors($form->get('controller_no')); ?>
          	</div>
		</div>
		<div class="row">
			<div class="row_title">
                <?php echo $this->formLabel($form->get('page_title')); ?>
                <span class="required">*</span>
            </div>
			<div class="row_details">
                <?php echo $this->formElement($form->get('page_title')); ?><br>
                <?php echo $this->formElementerrors($form->get('page_title')); ?>
           	</div>
		</div>
		<div class="row">
			<div class="row_title">
                <?php echo $this->formLabel($form->get('page_uri')); ?>
                <span class="required">*</span>
            </div>
			<div class="row_details">
                <?php echo $this->formElement($form->get('page_uri')); ?><br>
                <?php echo $this->formElementerrors($form->get('page_uri')); ?>
            </div>
		</div>
		<div class="row">
			<div class="row_title">
                <?php echo $this->formLabel($form->get('page_description')); ?>
            </div>
			<div class="row_details">
                <?php echo $this->formElement($form->get('page_description')); ?><br>
                <?php echo $this->formElementerrors($form->get('page_description')); ?>
            </div>
		</div>
		<div class="row">
			<div class="row_title">
                <?php echo $this->formLabel($form->get('icon')); ?>
            </div>
			<div class="row_details">
                <?php echo $this->formElement($form->get('icon')); ?>
			
<?php
    $attr = array(
        'url' => $this->url('app', array(
            'controller' => 'image',
            'action' => 'icon-list',
        )),
        'value' => $this->escapeHTML($this->translate('List')),
//        'value' => $this->escapeHTML($this->translate('リスト')),
        'class' => 'ctrl',
        'height' => 600,
        'width' => 1200,
    );
		echo $this->ViewButton()->printViewButton($attr) . "\n"; ?>
                <br>
                <?php echo $this->formElementerrors($form->get('icon')); ?>

           </div>
		</div>
        <div class="row">
			<div class="row_title">
                <?php echo $this->formLabel($form->get('use_mobile')); ?>
                <span class="required">*</span>
             </div>
			<div class="row_details">
                <?php echo $this->formElement($form->get('use_mobile')); ?><br>
                <?php echo $this->formElementerrors($form->get('use_mobile')); ?>
           </div>
		</div>
		<div class="row">
			<div></div>
			<div class="row_details">
		<?php
			echo $this->formSubmit($form->get('submit')) . "\n";
			echo $this->formReset($form->get('reset')) . "\n";
			echo $this->form()->closeTag();
		?>
			</div>
		</div>
	</div>
</div>
<br>

<script type="text/javascript">
<!-- //
    $(document).ready(function() {
        $('#submit').click(function() {
            if (progress) {
                return false;
            }
            else {
                progress = true;
                return $('#page_edit').submit();
            }
        });
    });
// -->
</script>

        <!-- pc/page/edit.phtml -->
