<?php
/**
 * ringi text template edit (PC)
 * author : Aruze Gaming America, Inc.
 */

$title = 'Text Template ' . ($this->action == 'add' ? 'Create' : 'Edit');
//$title = '稟議文書・テンプレート ' . ($this->action == 'add' ? '新規登録' : '編集');
$this->headTitle($title);

$this->headLink()
        ->prependStylesheet($this->basePath('css/pc/style_ui.css'));

$form = $this->form;
$form->setAttribute('action', $this->url('app', array(
        'controller' => 'tpl-document',
        'action' => $this->action,
        'id' => $this->id,
)));
$form->setAttribute('novalidate', 'novalidate');
?>

<script type="text/javascript">
<!-- //
<?php if(!$this->admin): ?>
    $(window).load(function() {
        $('#branch_no option').attr('disabled', true);
        $('#branch_no option:selected').attr('disabled', false);
    });
<?php endif; ?>

    $(function() {
        $('#tpl_body').resizable({
            minHeight: 215,
            minWidth:  500,
            maxHeight:  500,
            maxWidth:  500
        });


    	tinymce.init({
    		menubar:false,
    	    statusbar: false,
    	    toolbar: false,
    	    width: "200",
    	    height: "300",
    	   // toolbar: "code",
    	    selector: "textarea", 
    	    plugins: [
    			"code"
    	    ],
    	    valid_elements:"p",
    	   });
    });
// -->
</script>
<div id="title_bar">
	<h2><?php echo $title; ?></h2>
	<div id="content_arrow_sub"></div>
</div>
<div class="triangle-l"></div>
<ul class="breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>">Top</a></li>
    <li><span onclick="jump('<?php
            echo $this->url('app', array(
                    'controller' => 'tpl-document',
                    'action' => 'list',
                ));
            ?>');"><?php
                echo $this->escapeHTML($this->translate('Text Template List')); ?></span></li>
                <!--echo $this->escapeHTML($this->translate('稟議文書・テンプレート 一覧')); ?></span></li>-->
    <li><?php echo $this->escapeHTML($this->translate($title)); ?></li>
</ul>
<div class="clear"></div>
    <div class="err_msg"><?php
    if (isset($this->err_msg) && $this->err_msg) :
        echo "<br><br>";
        echo nl2br(
            $this->escapeHtml($this->translate($this->err_msg)), false);
    endif; ?></div>

   <div class="form_tpl">
<?php
    echo $this->form()->openTag($form) . "\n";
    echo $this->formHidden($form->get('token_id')) . "\n";
    echo $this->formHidden($form->get('tpl_doc_no')) . "\n";
    echo $this->formHidden($form->get('update_time')) . "\n";

    $error = $this->formElementerrors($form->get('token_id'));
    if ($error) :
        echo $error . "\n";
    endif;

    echo $this->formHidden($form->get('before_branch_no')) . "\n";
    echo $this->formHidden($form->get('before_tpl_title')) . "\n";
    echo $this->formHidden($form->get('before_tpl_body')) . "\n";

?>

    <div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('branch_no')); ?>
			<span class="required">*</span>
        </div>
		<div class="row_details">
			<?php echo $this->formElement($form->get('branch_no')); ?><br>
			<?php echo $this->formElementerrors($form->get('branch_no')); ?>
	   </div>
	</div>
	<div class="row">
		<div class="row_title">
                <?php echo $this->formLabel($form->get('tpl_title')); ?>
                <span class="required">*</span>
        </div>
		<div class="row_details">
			<?php echo $this->formElement($form->get('tpl_title')); ?><br>
			<?php echo $this->formElementerrors($form->get('tpl_title')); ?>
		</div>
	</div>
	<div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('tpl_body')); ?>
			<span class="required">*</span>
        </div>
		<div class="row_details">
			<?php echo $this->formElement($form->get('tpl_body')); ?><br>
			<div class="err_msg right"><?php
				echo $this->escapeHTML(
						sprintf($this->translate('Max %s Characters'), '1000')); ?>
			</div>
						<!--sprintf($this->translate('最大 %s 文字'), '1000')); ?>-->
			<?php echo $this->formElementerrors($form->get('tpl_body')); ?>
        </div>
	</div>
	<div class="row">
		<div></div>
		<div class="row_details">
		<?php
			echo $this->formSubmit($form->get('submit')) . "\n";
			echo $this->formReset($form->get('reset')) . "\n";
			echo $this->form()->closeTag();
		?>
		</div>
	</div>
</div>
<br>

<script type="text/javascript">
<!-- //
    $(document).ready(function() {
        $('#submit').click(function() {
            if (progress) {
                return false;
            }
            else {
                progress = true;
                return $('#tpl-document_edit').submit();
            }
        });
    });
// -->
</script>

        <!-- pc/tpl-document/edit.phtml -->
