<?php
/**
 * user edit (PC)
 * author : Aruze Gaming America, Inc.
 */

$title = !$this->id ? 'User Create'
//$title = !$this->id ? 'ユーザ 登録'
        : ($this->self ? 'My Account Edit' : 'User Edit');
//        : ($this->self ? 'Myアカウント 編集' : 'ユーザ 編集');
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('app', array(
        'controller' => 'user',
        'action' => $this->action,
        'id' => $this->id,
)));
$form->setAttribute('novalidate', 'novalidate');
?>

<script type="text/javascript">
<!-- //
    $(window).load(function() {
<?php if ($this->self) : ?>

        $('#section_no option').attr('disabled', true);
        $('#section_no option:selected').attr('disabled', false);

        $('#position_no option').attr('disabled', true);
        $('#position_no option:selected').attr('disabled', false);

        $('input[name=valid]').attr('disabled', true);
        $('input[name=valid]:checked').attr('disabled', false);
<?php
endif;

if (!$this->admin || $this->self): ?>

        $('#branch_no option').attr('disabled', true);
        $('#branch_no option:selected').attr('disabled', false);
<?php endif; ?>

    });

<?php if ($this->admin): ?>

    $(function() {
        $('#branch_no').change(function() {
            var branch_no = $('#branch_no').val();
            var url = '<?php
                echo $this->url('app', array(
                    'controller' => 'section',
                    'action' => 'get-select',
                )); ?>';
            var data = 'branch_no=' + branch_no + '&type=edit';

            $.ajax({
                type: 'POST',
                url: url,
                data: data,
                success: function(res) {
                    $('#section_cell').html(res);
                }
            });

            var url = '<?php
                echo $this->url('app', array(
                    'controller' => 'position',
                    'action' => 'get-select',
                )); ?>';
            var data = 'branch_no=' + branch_no + '&type=edit';

            $.ajax({
                type: 'POST',
                url: url,
                data: data,
                success: function(res) {
                    $('#position_cell').html(res);
                }
            });
        });
    });

<?php endif; ?>
// -->
</script>
<div id="title_bar">
	<h2><?php echo $title; ?></h2>
	<div id="content_arrow_sub"></div>
</div>
<div class="triangle-l"></div>
<ul class="breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>">Top</a></li>
<?php if (!$this->self) : ?>
    <li><span onclick="jump('<?php
            echo $this->url('app', array(
                    'controller' => 'user',
                    'action' => 'list',
                ));
            ?>');"><?php
                echo $this->escapeHTML($this->translate('User List')); ?></span></li>
                <!--echo $this->escapeHTML($this->translate('ユーザ 一覧')); ?></span></li>-->
<?php endif; ?>

    <li><?php echo $this->escapeHTML($this->translate($title)); ?></li>
</ul>
<div class="clear"></div>

    <div class="err_msg"><?php
    if (isset($this->err_msg) && $this->err_msg) :
        echo "<br><br>";
        echo nl2br(
            $this->escapeHtml($this->translate($this->err_msg)), false);
    endif; ?></div>
     <br>
	<div class="form_center">
<?php
    echo $this->form()->openTag($form) . "\n";
    echo $this->formHidden($form->get('token_id')) . "\n";
    echo $this->formHidden($form->get('user_no')) . "\n";
    echo $this->formHidden($form->get('update_time')) . "\n";
    if (!$this->admin || $this->self) :
        echo $this->formHidden($form->get('admin')) . "\n";
    endif;

    echo $this->formHidden($form->get('before_user_name')) . "\n";
    echo $this->formHidden($form->get('before_branch_no')) . "\n";

    echo $this->formHidden($form->get('before_section_no')) . "\n";
    echo $this->formHidden($form->get('before_position_no')) . "\n";
    echo $this->formHidden($form->get('before_email')) . "\n";
    echo $this->formHidden($form->get('before_phone')) . "\n";
    echo $this->formHidden($form->get('before_timezone')) . "\n";
    echo $this->formHidden($form->get('before_lang_no')) . "\n";
    echo $this->formHidden($form->get('before_valid')) . "\n";
    echo $this->formHidden($form->get('before_admin')) . "\n";


    $error = $this->formElementerrors($form->get('token_id'));
    if ($error) :
        echo $error . "\n";
    endif;
?>

<?php if ('add' == $this->action) : ?>
    <div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('login_id')); ?>
			<span class="required">*</span>
	   </div>
		<div class="row_details">
			<?php echo $this->formElement($form->get('login_id')); ?>
			<?php echo $this->formElementerrors($form->get('login_id')); ?>
	   </div>
	</div>
<?php endif; ?>
	<div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('branch_no')); ?>
			<span class="required">*</span>
        </div>
		<div class="row_details">
			<?php echo $this->formElement($form->get('branch_no')); ?>
			<?php echo $this->formElementerrors($form->get('branch_no')); ?>
		</div>
	</div>
	<div class="row">
		<div class="row_title">
            <?php echo $this->formLabel($form->get('user_name')); ?>
                <span class="required">*</span>
        </div>
		<div class="row_details">
			<?php echo $this->formElement($form->get('user_name')); ?>
			<?php echo $this->formElementerrors($form->get('user_name')); ?>
         </div>
	</div>
    <div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('section_no')); ?>
			<span class="required">*</span>
        </div>
		<div class="row_details">
				<div id="section_cell">
				<?php echo $this->formElement($form->get('section_no')); ?>
				</div>
			<?php echo $this->formElementerrors($form->get('section_no')); ?>
		</div>
	</div>
    <div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('position_no')); ?>
			<span class="required">*</span>
        </div>
		<div class="row_details">
			<div id="position_cell">
			<?php echo $this->formElement($form->get('position_no')); ?>
			</div>
			<?php echo $this->formElementerrors($form->get('position_no')); ?>
		</div>
	</div>
	<div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('immediate_superior_no')); ?>
			<span class="required">*</span>
        </div>
		<div class="row_details">
			<div id="position_cell">
			<?php echo $this->formElement($form->get('immediate_superior_no')); ?>
			</div>
			<?php echo $this->formElementerrors($form->get('immediate_superior_no')); ?>
		</div>
	</div>
    <div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('email')); ?>
			<span class="required">*</span>
		</div>
		<div class="row_details">
			<?php echo $this->formElement($form->get('email')); ?>
			<?php echo $this->formElementerrors($form->get('email')); ?>
        </div>
	</div>
    <div class="row">
		<div class="row_title">
           <?php echo $this->formLabel($form->get('phone')); ?>
        </div>
		<div class="row_details">
			<?php echo $this->formElement($form->get('phone')); ?>
			<?php echo $this->formElementerrors($form->get('phone')); ?>
		</div>
	</div>
    <div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('timezone')); ?>
        </div>
		<div class="row_details">
			<?php echo $this->formElement($form->get('timezone')); ?>
			<?php echo $this->formElementerrors($form->get('timezone')); ?>
		</div>
	</div>
    <div class="row">
		<div class="row_title">
           <?php echo $this->formLabel($form->get('lang_no')); ?>
        </div>
		<div class="row_details">
                <?php echo $this->formElement($form->get('lang_no')); ?>
                <?php echo $this->formElementerrors($form->get('lang_no')); ?>
        </div>
	</div>
<?php if ($this->admin && !$this->self) : ?>
    <div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('admin')); ?>
        </div>
		<div class="row_details">
                <?php echo $this->formElement($form->get('admin')); ?>
        </div>
	</div>
<?php endif; ?>

<?php if ($this->self) : ?>
    <div class="row">
		<div class="row_title">
         <?php echo $this->escapeHTML($this->translate('Password')); ?>
		</div>
		<div class="row_details">
			<button type="button" onclick="jump('<?php
				echo $this->url('app', array(
					'controller' => 'index',
					'action' => 'change-pw',
				));?>');"><?php
				echo $this->escapeHTML($this->translate('Change'));
				?></button>
		</div>
	</div>
<?php endif; ?>
    <div class="row">
		<div class="row_title">
                <?php echo $this->formLabel($form->get('valid')); ?>
                <span class="required">*</span>
		</div>
		<div class="row_details">
                <?php echo $this->formElement($form->get('valid')); ?><br>
                <?php echo $this->formElementerrors($form->get('valid')); ?>
       	</div>
	</div>
	 <div class="row">
		<div></div>
		<div class="row_details">
		<?php
			echo $this->formSubmit($form->get('submit')) . "\n";
			echo $this->formReset($form->get('reset')) . "\n";
			echo $this->form()->closeTag();
		?>
		</div>
	</div>
<script type="text/javascript">
<!-- //
    $(document).ready(function() {
        $('#submit').click(function() {
            if (progress) {
                return false;
            }
            else {
                progress = true;
                return $('#user_edit').submit();
            }
        });
    });
// -->
</script>
	</div>
        <!-- pc/user/edit.phtml -->
