<?php
/**
 * request category list (PC)
 * author : Aruze Gaming America, Inc.
 */

$title = 'Requests Category Edit';
//$title = 'ページ・カテゴリ 一覧';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('app', array(
        'controller' => 'request-category',
        'action' => 'edit',
        'id' => $this->id,
)));

$form->prepare();

echo $this->PageCtrl()->getNaviJs();
?>

<script type="text/javascript">
<!-- //
    function createChild(_id) {

     alert('create Child using '+ _id +' as parent id ');
    
    }
// -->
</script>
<style>
.menu-item {
	padding: 10px;
	border-left: 1px solid #E6E6E6;
	width: 220px;
	float: left;
	margin-bottom: 35px;
	border-bottom: 1px solid #E6E6E6;
}

.menu-item ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
}

.menu-item ul li {
	padding-left: 15px;
	min-height: 29px;
	padding-top: 12px;
}

#btn-submit {
	padding-left: 5px;
	padding-right: 5px;
}
</style>
<div id="title_bar">
	<h2><?php echo $title; ?></h2>
	<div id="content_arrow_sub"></div>
</div>
<div class="triangle-l"></div>
<ul class="breadcrumb">
	<li><a href="<?php echo BASE_URL; ?>">Top</a></li>
	<li><?php echo $this->escapeHTML($this->translate($title)); ?></li>
</ul>
<div class="clear"></div>
<div id="main">
	<div class="msg_box">
<?php
    if ($this->message) :
        echo $this->escapeHTML($this->translate($this->message));
    endif;
 ?>
    </div>
	<br>

	<div style="with: 500px; margin-left: 50px; margin-bottom: 20px">
		<div>
			<!-- a href="#">expenses</a> / <a href="#">purchase</a>  / <select><option>CEO</option><option>Manager</option><option>Assistant Manager</option></select> <button>Assign</button // -->
		</div>
	</div>

	<div class="list_box">
		<a href="<?php echo $this->url('app',array('controller'=>'request-category','action'=>'list'))?>">TOP</a>
           <?php 
           $array_count =  count($this->menu_route);
         
           if($this->menu_route):
           foreach ($this->menu_route as $route): ?>
           <?php $array_count -- ;?>
            <?php if($array_count > 0):?>
               / <a href="<?php echo $this->url('app',array('controller'=>'request-category','action'=>'list','id'=>$route['id']))?>"><?php echo $route["menu_item_name"]?></a>
            <?php endif;?>
           <?php endforeach;?>
           <?php endif;?>
        <hr/>
		<div class="menu-item">
		<?php echo $this->form()->openTag($form);?>
		<?php echo $this->formHidden($form->get('id'));?>
		<?php echo $this->formHidden($form->get('parent_id'));?>
			<ul>
				<li>
				  <?php  echo $this->formRow($form->get('menu_item_name')); ?>
				</li>
				<li>
				  <?php  echo $this->formRow($form->get('menu_item_code')); ?>
				</li>
				<li>
				<?php  echo $this->formRow($form->get('position_no')); ?>
				</li>
				
				<li>
					<p><button>Save Changes</button></p>
				</li>
			</ul>
			<?php  echo $this->form()->closeTag();?>
		</div>

	</div>


</div>
<br>

