<?php
/**
 * branch list (PC)
 * author : Aruze Gaming America, Inc.
 */

$title = 'Branch List';
//$title = '支社 一覧';
$this->headTitle($title);

$form = $this->form;

echo $this->PageCtrl()->getNaviJs();
?>

<script type="text/javascript">
<!-- //
    function delete_btn(id) {
        if (progress) {
            return false;
        }
        progress = true;
        var url = '<?php
        echo $this->url('app', array(
                    'controller' => 'branch',
                    'action' => 'delete',
                ));
        ?>/' + id;

        $.ajax({
            type: 'POST',
            url: url,
            success: function() {
                location.reload();
            }
        });
    }

    function restore_btn(id) {
        if (progress) {
            return false;
        }
        progress = true;
        var url = '<?php
        echo $this->url('app', array(
                    'controller' => 'branch',
                    'action' => 'restore',
                ));
        ?>/' + id;

        $.ajax({
            type: 'POST',
            url: url,
            success: function() {
                location.reload();
            }
        });
    }
// -->
</script>

<ul class="breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>">Top</a></li>
    <li><?php echo $this->escapeHTML($this->translate($title)); ?></li>
</ul>

<div id="main">
    <div class="msg_box">
<?php
    if ($this->message) :
        echo $this->escapeHTML($this->translate($this->message));
    endif;
 ?>
    </div>
    <br>

    <div class="right_box">
<?php
    $jump = "";
    if (1 < $this->ctrlLv) :
        $jump = ' onclick="jump(\''
            . $this->url('app', array(
                'controller' => 'branch',
                'action' => 'add',
            ))
            . '\');"';
    endif;
?>
        <button type="button" class="ctrl<?php
                echo !$jump ? ' disabled' : '';
                ?>"<?php
                echo $jump; ?>><?php
                echo $this->escapeHTML($this->translate('create'));
//                echo $this->escapeHTML($this->translate('新規'));
            ?></button>
    </div>

    <!-- search_box -->
    <div class="search_box">
<?php
        echo $this->form()->openTag($form) . "\n";
        echo $this->formHidden($form->get('ord')) . "\n";
?>

        <table class="search">
            <tbody>
                <tr>
                    <th><?php echo $this->formLabel($form->get('search-branch_name')); ?></th>
                    <td><?php echo $this->formElement($form->get('search-branch_name')); ?></td>
                    <th><?php echo $this->formLabel($form->get('search-abbr_name')); ?></th>
                    <td><?php echo $this->formElement($form->get('search-abbr_name')); ?></td>
                </tr>
                <tr>
                    <th><?php echo $this->formLabel($form->get('search-phone')); ?></th>
                    <td><?php echo $this->formElement($form->get('search-phone')); ?></td>
                    <th><?php echo $this->formLabel($form->get('search-address')); ?></th>
                    <td><?php echo $this->formElement($form->get('search-address')); ?></td>
                </tr>
            </tbody>
        </table>
<?php
    echo $this->formElement($form->get('submit')) . "\n";
    echo $this->formElement($form->get('clear')) . "\n";
    echo $this->form()->closeTag();
?>

    </div>
    <!-- search_box -->
    <br><br>

    <!-- list_box -->
    <div class="list_box">
        <table class="list">
            <caption>
                <?php echo $this->PageCtrl()->getNavi($this->page); ?>
            </caption>
            <thead>
                <tr>
                    <th class="ctrl"><?php
                        echo $this->escapeHTML($this->translate('Edit')); ?></th>
                        <!--echo $this->escapeHTML($this->translate('編集')); ?></th>-->

                    <th class="branch"><?php
                        echo $this->escapeHTML($this->translate('Branch Name'));
//                        echo $this->escapeHTML($this->translate('支社名'));
                        echo $this->PageCtrl()->getOrderLink('branch_name');
                        ?></th>
                    <th class="abbr"><?php
                        echo $this->escapeHTML($this->translate('Abbr'));
//                        echo $this->escapeHTML($this->translate('略称'));
                        echo $this->PageCtrl()->getOrderLink('abbr_name');
                        ?></th>
                    <th class="text"><?php
                        echo $this->escapeHTML($this->translate('Timezone '));
                        echo $this->PageCtrl()->getOrderLink('timezone');
                        ?></th>
                    <th class="phone"><?php
                        echo $this->escapeHTML($this->translate('Tel'));
//                        echo $this->escapeHTML($this->translate('代表番号'));
                        echo $this->PageCtrl()->getOrderLink('phone');
                        ?></th>
                    <th class="text"><?php
                        echo $this->escapeHTML($this->translate('Address'));
//                        echo $this->escapeHTML($this->translate('所在地'));
                        echo $this->PageCtrl()->getOrderLink('address');
                        ?></th>
                    <th class="user"><?php
                        echo $this->escapeHTML($this->translate('Create User'));
//                        echo $this->escapeHTML($this->translate('登録者'));
                        echo $this->PageCtrl()->getOrderLink('create_user');
                        ?></th>
                    <th class="date"><?php
                        echo $this->escapeHTML($this->translate('Create Time'));
//                        echo $this->escapeHTML($this->translate('登録日時'));
                        echo $this->PageCtrl()->getOrderLink('create_time');
                        ?></th>
                    <th class="user"><?php
                        echo $this->escapeHTML($this->translate('Update User'));
//                        echo $this->escapeHTML($this->translate('最終更新者'));                        
                        echo $this->PageCtrl()->getOrderLink('update_user');
                        ?></th>
                    <th class="date"><?php
                        echo $this->escapeHTML($this->translate('Update Time'));
//                        echo $this->escapeHTML($this->translate('最終更新日時'));
                        echo $this->PageCtrl()->getOrderLink('update_time');
                        ?></th>
                    <th class="ctrl"><?php
                        echo $this->escapeHTML($this->translate('Delete')); ?></th>
                        <!--echo $this->escapeHTML($this->translate('削除')); ?></th>-->
                </tr>
            </thead>
            <tbody>
<?php
    foreach ($this->rows as $row) {
?>
                <tr<?php echo gv('deleted', $row) ? ' class="deleted"' : ''; ?>>
                    <td class="ctrl">
<?php
    $jump = "";
    if (2 < $this->ctrlLv) :
        $jump = ' onclick="jump(\''
            . $this->url('app', array(
                'controller' => 'branch',
                'action' => 'edit',
                'id' => gv('branch_no', $row)
            ))
            . '\');"';
    endif;
?>
                        <button type="button" class="ctrl" <?php
                            echo $jump; ?><?php
                            echo gv('deleted', $row) || !$jump ? ' disabled=disabled' : '';
                            ?>><?php
                            echo $this->escapeHTML($this->translate('Edit'));
//                            echo $this->escapeHTML($this->translate('編集'));
                        ?></button>
                    </td>
                    <td class="branch"><?php
                        echo $this->escapeHTML(gv('branch_name', $row)); ?></td>
                    <td class="abbr"><?php
                        echo $this->escapeHTML(gv('abbr_name', $row)); ?></td>
                    <td class="text"><?php
                        echo $this->escapeHTML(gv('timezone', $row)); ?></td>
                    <td class="phone tooltip" title="<?php
                        echo $this->escapeHTML(gv('phone', $row)); ?>"><?php
                        echo $this->escapeHTML(gv('phone', $row)); ?></td>
                    <td class="text tooltip" title="<?php
                        echo $this->escapeHTML(gv('address', $row)); ?>"><?php
                        echo $this->escapeHTML(gv('address', $row)); ?></td>
                    <td class="user"><?php
                        echo $this->escapeHTML(gv('create_user', $row)); ?></td>
                    <td class="date"><?php
                        echo $this->escapeHTML(gv('create_time', $row)); ?></td>
                    <td class="user"><?php
                        echo $this->escapeHTML(gv('update_user', $row)); ?></td>
                    <td class="date"><?php
                        echo $this->escapeHTML(gv('update_time', $row)); ?></td>

                    <td class="ctrl">
                        <button type="button" onclick="<?php
                            echo gv('deleted', $row) ? 'restore' : 'delete';
                            ?>_btn('<?php
                            echo gv('branch_no', $row); ?>');" class="ctrl"<?php
                            echo 4 > $this->ctrlLv ? ' disabled=disabled' : '';
                            ?>><?php
                            echo $this->escapeHTML(
                                    $this->translate((gv('deleted', $row) ? 'Restore' : 'Delete')));
//                                    $this->translate((gv('deleted', $row) ? '復帰' : '削除')));
                        ?></button>
                    </td>
                </tr>
<?php
    }
?>

            </tbody>
        </table>
    </div>
    <!-- list_box -->

</div>
<br>
        <!-- pc/branch/list.phtml -->
