<?php
/**
 * change password input (PC)
 * author : Aruze Gaming America, Inc.
 */

$this->headTitle('Change Password');
$url = $this->url(
    'app',
    array(
        'controller' => 'index',
        'action' => 'update-pw',
    )
);
?>

<script type="text/javascript">
<!-- //
    $(document).ready(function() {
        $('#reset').click(function() {
            if (progress) {
                return false;
            }
            else {
                $('#input_pw_old').val("");
                $('#input_pw_new').val("");
                $('#input_pw_confirm').val("");
                $('#login_id').val("");
                $('#login_pw').val("");
            }
            return;
        });

        $('#change_pw').click(function() {
            change_pw_btn();
        });

        $(window).keyup(function(e) {
            if ("13" == e.keyCode) {
                change_pw_btn();
            }
        });
    });

    function change_pw_btn() {
        var id = $('#login_id').val();
        var old_pw = $('#input_pw_old').val();
        var new_pw = $('#input_pw_new').val();
        var con_pw = $('#input_pw_confirm').val();
        var sid = $('#token_id').val();

        if (!id || !old_pw || !new_pw || !con_pw || !sid || progress) {
            return false;
        }
        else if (new_pw !== con_pw) {
            alert("<?php
                echo $this->translate("Password do not match");
//                echo $this->translate("確認用のパスワードが一致しません。");
                ?>");
        }
        else if (old_pw === new_pw) {
            alert("<?php
                echo $this->translate("Can't use same password");
//                echo $this->translate("変更後のパスワードが同じです。");
                ?>");
        }
        else {
            progress = true;
            $('#login_pw').val(hex_md5(old_pw + sid));
            $('#new_pw').val(new_pw);
            $('#key_id').val(hex_md5(old_pw));
            return $('#chg_frm').submit();
        }
    }

    function check_pw_string(str) {

    }
// -->
</script>

<div id="top_box">
    <header id="logo">
        <a href="<?php echo BASE_URL; ?>">
            <img src="<?php echo $this->basePath('img/logo.png'); ?>" alt="AruzeGaming">
        </a>
    </header>
    <br>

    <div class="err_msg"><?php
    if (isset($this->err_msg) && $this->err_msg) :
        $msg = explode("\n", $this->err_msg);
        $str = current($msg);
        do {
            next($msg);
            echo $str ? $this->escapeHtml($this->translate($str)) : "";
            echo "<br>\n";
        } while($str = current($msg));
    endif;
    ?></div>

    <form id="chg_frm" name="chg_frm" action="<?php echo $url; ?>" method="post">
        <input type="hidden" id="login_pw" name="login_pw" value="">
        <input type="hidden" id="new_pw" name="new_pw" value="">
        <input type="hidden" id="key_id" name="key_id" value="">
        <input type="hidden" id="token_id" name="token_id" value="<?php
            echo $this->escapeHtml($this->token_id); ?>">

        <input type="text" id="login_id" name="login_id" value="<?php
            echo $this->escapeHtml($this->login_id);
            ?>" placeholder="LOGIN ID" autocomplete="off" autofocus require><br>
  
    <input type="password" id="input_pw_old" name="input_pw_old" value="" placeholder="OLD PASSWORD" autocomplete="off" require><br>
    <input type="password" id="input_pw_new" name="input_pw_new" value="" placeholder="NEW PASSWORD" autocomplete="off" require><br>
    <input type="password" id="input_pw_confirm" name="input_pw_confirm" value="" placeholder="CONFIRM PASSWORD" autocomplete="off" require><br>
    <input type="submit" id="change_pw" name="change_pw" value="Change PW" >
    <input type="reset" id="reset_pw" name="reset_pw" value="Reset">
	</form>
</div>
        <!-- pc/index/change-pw.phtml -->
