<?php
/**
 * section edit (PC)
 * author : Aruze Gaming America, Inc.
 */

$title = 'Section ' . ($this->action == 'add' ? 'Create' : 'edit');
//$title = '部署 ' . ($this->action == 'add' ? '新規登録' : '編集');
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('app', array(
        'controller' => 'section',
        'action' => $this->action,
        'id' => $this->id,
)));
$form->setAttribute('novalidate', 'novalidate');
?>

<script type="text/javascript">
<!-- //
<?php if(!$this->admin): ?>

    $(window).load(function() {
        $('#branch_no option').attr('disabled', true);
        $('#branch_no option:selected').attr('disabled', false);
    });
<?php endif; ?>

// -->
</script>
<div id="title_bar">
	<h2><?php echo $title; ?></h2>
	<div id="content_arrow_sub"></div>
</div>
<div class="triangle-l"></div>
<ul class="breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>">Top</a></li>
    <li><span onclick="jump('<?php
            echo $this->url('app', array(
                    'controller' => 'section',
                    'action' => 'list',
                ));
            ?>');"><?php
                echo $this->escapeHTML($this->translate('Section List')); ?></span></li>
                <!--echo $this->escapeHTML($this->translate('部署 一覧')); ?></span></li>-->
    <li><?php echo $this->escapeHTML($this->translate($title)); ?></li>
</ul>
<div class="clear"></div>
<div id="main">
    <div class="err_msg"><?php
    if (isset($this->err_msg) && $this->err_msg) :
        echo "<br><br>";
        echo nl2br(
            $this->escapeHtml($this->translate($this->err_msg)), false);
    endif; ?></div>

    <br>
	<div class="form_center">
<?php
    echo $this->form()->openTag($form) . "\n";
    echo $this->formHidden($form->get('token_id')) . "\n";
    echo $this->formHidden($form->get('section_no')) . "\n";
    echo $this->formHidden($form->get('update_time')) . "\n";

    $error = $this->formElementerrors($form->get('token_id'));
    if ($error) :
        echo $error . "\n";
    endif;

    echo $this->formHidden($form->get('before_branch_no')) . "\n";
    echo $this->formHidden($form->get('before_section_name')) . "\n";
    echo $this->formHidden($form->get('before_abbr_name')) . "\n";

?>

    <div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('branch_no')); ?>
			<span class="required">*</span>
		</div>
		<div class="row_details">
			<?php echo $this->formElement($form->get('branch_no')); ?><br>
			<?php echo $this->formElementerrors($form->get('branch_no')); ?>
        </div>
	</div>
	<div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('section_name')); ?>
			<span class="required">*</span>
		</div>
		<div class="row_details">
			<?php echo $this->formElement($form->get('section_name')); ?><br>
			<?php echo $this->formElementerrors($form->get('section_name')); ?>
		</div>
	</div>
	<div class="row">
		<div class="row_title">
			<?php echo $this->formLabel($form->get('abbr_name')); ?>
		</div>
		<div class="row_details">
			<?php echo $this->formElement($form->get('abbr_name')); ?><br>
			<?php echo $this->formElementerrors($form->get('abbr_name')); ?>
		</div>
	</div>
	<div class="row">
		<div>
		
		</div>
		<div class="row_details">
		<?php
			echo $this->formSubmit($form->get('submit')) . "\n";
			echo $this->formReset($form->get('reset')) . "\n";
			echo $this->form()->closeTag();
		?>
		</div>
	</div>

</div>
</div>
<br>

<script type="text/javascript">
<!-- //
    $(document).ready(function() {
        $('#submit').click(function() {
            if (progress) {
                return false;
            }
            else {
                progress = true;
                return $('#section_edit').submit();
            }
        });
    });
// -->
</script>

        <!-- pc/section/edit.phtml -->
