<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<div class="login-form" style="width: 95%; margin:27% auto">
			<div class="box box-info">
				<div class="box-header text-center">
					<div>
						<img src="/img/logo.png" width="250" height="25">
					</div>
					<h2 class="page-header">Game Detail Information</h2>
				</div>
				<!-- /.box-header -->
				<!-- form start -->
				<form class="form-horizontal">
					<div class="box-body">
						<div class="form-group">
						     
						     <p class="text-center"> <small>Please enter your email address and we will send you the password</small> </p>
							<label for="inputEmail3" class="col-sm-2 control-label">Email</label>
							<div class="col-sm-10">
								<input type="email" class="form-control" id="inputEmail3"
									placeholder="Enter email address">
							</div>
						</div>
					</div>
						<p class="text-center">
					<?php echo $this->render('flashmessenger/layout')?></p>
					<!-- /.box-body -->
					<div class="box-footer">
						<button type="submit" class="btn btn-default">reset</button>
						<button type="submit" class="btn btn-info pull-right">Send
							password</button>
					</div>

					<div class="pull-right hidden-xs">
						<p></p>
						<a href="<?php echo $this->url('auth',array('action'=>'index'))?>"><b>login</b></a>
					</div>
					<!-- /.box-footer -->
				</form>

			</div>
		</div>
	</div>
	<div class="col-md-3"></div>
</div>