<?php
/**
 * controller edit (PC)
 * author : Aruze Gaming America, Inc.
 */

$title = 'Controller ' . ($this->action == 'add' ? 'Create' : 'Edit');
//$title = 'コントローラ ' . ($this->action == 'add' ? '新規登録' : '編集');

$form = $this->form;
$form->setAttribute('action', $this->url('app', array(
        'controller' => 'controller',
        'action' => $this->action,
        'id' => $this->id,
)));
$form->setAttribute('novalidate', 'novalidate');

$this->headTitle($title);
?>
<div id="title_bar">
	<h2><?php echo $title; ?></h2>
	<div id="content_arrow_sub"></div>
</div>
<div class="triangle-l"></div>
<ul class="breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>">Top</a></li>
    <li><span onclick="jump('<?php
            echo $this->url('app', array(
                    'controller' => 'controller',
                    'action' => 'list',
                ));
            ?>');"><?php
                echo $this->escapeHTML($this->translate('Controller List')); ?></span></li>
                <!--echo $this->escapeHTML($this->translate('コントローラ 一覧')); ?></span></li>-->    
    <li><?php echo $this->escapeHTML($this->translate($title)); ?></li>
</ul>

<div id="main">
    <div class="err_msg"><?php
    if (isset($this->err_msg) && $this->err_msg) :
        echo "<br><br>";
        echo nl2br(
            $this->escapeHtml($this->translate($this->err_msg)), false);
    endif; ?></div>

    <br>
	<div class="form_center">
<?php
    echo $this->form()->openTag($form) . "\n";
    echo $this->formHidden($form->get('token_id')) . "\n";
    echo $this->formHidden($form->get('controller_no')) . "\n";
    echo $this->formHidden($form->get('update_time')) . "\n";

    echo $this->formHidden($form->get('before_controller_name')) . "\n";
    echo $this->formHidden($form->get('before_ctrl_description')) . "\n";

    $error = $this->formElementerrors($form->get('token_id'));
    if ($error) :
        echo $error . "\n";
    endif;
?>
		<div class="row">
			<div class="row_title">
			<?php echo $this->formLabel($form->get('controller_name')); ?>
			<span class="required">*</span>
			</div>
			<div class="row_details">
			<?php echo $this->formElement($form->get('controller_name')); ?>
			<?php echo $this->formElementerrors($form->get('controller_name')); ?>
			</div>
		</div>
		<div class="row">
			<div class="row_title">
			<?php echo $this->formLabel($form->get('ctrl_description')); ?>
			</div>
			<div class="row_details">
			<?php echo $this->formElement($form->get('ctrl_description')); ?>
			<?php echo $this->formElementerrors($form->get('ctrl_description')); ?>
			</div>
		</div>
		<div class="row">
			<div></div>
			<div class="row_details">
			<?php
				echo $this->formSubmit($form->get('submit')) . "\n";
				echo $this->formReset($form->get('reset')) . "\n";
				echo $this->form()->closeTag();
			?>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
<!-- //
    $(document).ready(function() {
        $('#submit').click(function() {
            if (progress) {
                return false;
            }
            else {
                progress = true;
                return $('#controller_edit').submit();
            }
        });
    });
// -->
</script>

        <!-- pc/controller/edit.phtml -->
