<?php
/**
 * Controller Skelton
 * author : Aruze Gaming America, Inc.
 */

$nameId = $this->nameId;
$baseFolder = $this->baseFolder;
$ctrl = $nameId . 'Controller';
$entity = $nameId . 'Entity';
$form = $nameId . 'Form';
$filter = $nameId . 'Filter';

header("Content-type: application/octet-stream");
header("Content-Disposition: attachment; filename=\"{$ctrl}.php\"");

echo '<?php'; ?>

/**
 * Zend Framework (http://framework.zend.com/)
 *
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2015 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace App\Controller;
use Zend\View\Model\ViewModel;
use App\Controller\AbstractController;
use App\Model\Entity\<?php echo $entity; ?>;
use App\Form\<?php echo $form; ?>;
use App\Filter\<?php echo $filter; ?>;

class <?php echo $ctrl; ?> extends AbstractController
{
    public function __construct()
    {
    }

    /**
     * 一覧表示
     * @return ViewModel
     */
    public function listAction()
    {
        $this->init();
        $success = (0 < $this->ctrlLv) ? true : false;
        if (!$success) {
            return $this->redirect()->toRoute('app', array(
                'controller' => 'failed', 'action' => 'forbidden'
            ));
        }
        $fm = $this->flashMessenger();
        $message = gv('0', $fm->getMessages());

        // GETメソッドから検索値を取得
        $param = $this->search()->getSearchParam();
        if ($param) {
            $this->container()->set('search', json_encode($param));
        }
        else {
            $param = $this->container()->get('search');
            $param = json_decode($param, true);
        }
<?php if ($this->branch) : ?>

        // 所属 branch をセット
        if (!$this->auth()->get('admin')) {
            $param['search-branch_no'] = $this->auth()->get('branch_no');
        }

<?php endif; ?>

        // ToDo : 必要な処理を実装せよ
        $form = new <?php echo $form; ?>();
        $form->setListForm();
        if ($param) {
            $form->bind(get_array_object($param));
        }
        $form->get('submit')->setAttribute('value', '検索');

        $where = $this->search()->getSearchParamConv($param);
        if (4 > $this->ctrlLv) {
            $where = array_merge($where, array('deleted' => 0));
        }

        $order = $this->search()->getOrder();
        $current = $this->search()->getPage();
        $max = $this->search()->getDisplayNum();

        $db = new <?php echo $entity; ?>();
        $page = $db->db()->getPageList($where, $order, $current, $max);

        $values = array(
            'ctrlLv' => $this->ctrlLv,
            'rows' => $page->getCurrentItems()->toArray(),
            'page' => $page->getPages(),
            'form' => $form,
            'admin' => $this->auth()->get('admin'),
            'message' => $message,
        );
        $view = new ViewModel($values);
        $view->setTemplate('/' . VIEW_DIR . '/<?php echo $baseFolder ?>/list.phtml');
        return $view;
    }
<?php if ($this->use_detail) : ?>

    /**
     * 情報表示
     * @return ViewModel
     */
    public function detailAction()
    {
        $id = (int) $this->params()->fromRoute('id', 0);
        if (!$id) {
            return $this->redirect()->toUrl(BASE_URL);
        }

        $this->init();
        $success = (0 < $this->ctrlLv) ? true : false;

        if (!$success) {
            return $this->redirect()->toRoute('app', array(
                'controller' => 'failed', 'action' => 'forbidden'
            ));
        }
        $db = new <?php echo $entity; ?>();
        $row = $db->db()->getFetchOne($id);
        $success = false;
        if (!$row) {
            $this->flashMessenger()->addMessage('指定レコードは存在しません。');
        }
<?php if ($this->branch) : ?>

        else if (!$this->auth()->get('admin')
                && $this->auth()->get('branch_no') != $row->branch_no) {
            $this->flashMessenger()->addMessage('許可されていません。');
        }
<?php endif; ?>

        else {
            $success = true;
        }

        if (!$success) {
            return $this->redirect()->toRoute('app', array(
                'controller' => 'failed', 'action' => 'index'
            ));
        }

        $values = array(
            'ctrlLv' => $this->ctrlLv,
            'row' => $row,
        );

        $view = new ViewModel($values);
        $view->setTemplate('/' . VIEW_DIR . '/<?php echo $baseFolder ?>/detail.phtml');
        $view->setTerminal(true);
        return $view;
    }
<?php endif; ?>

    /**
     * 新規登録用編集画面 + 挿入処理
     * @return ViewModel
     */
    public function addAction()
    {
        $this->init();

        // 権限チェック
        $success = (1 < $this->ctrlLv) ? true : false;
        if (!$success) {
            return $this->redirect()->toRoute('app', array(
                'controller' => 'failed', 'action' => 'forbidden'
            ));
        }

        // ToDo : 必要な処理を実装せよ
        $form = new <?php echo $form; ?>();
        $form->setEditForm();
        $db = new <?php echo $entity; ?>();
        $filter = new <?php echo $filter; ?>();

        $request = $this->getRequest();
        // POST無 編集画面描画
        if (!$request->isPost()) {
            $postRequest = $this->container()->get('postRequest');
            if ($postRequest) {
                $this->container()->clear('postRequest');
                $row = get_array_object(json_decode($postRequest, true));
                $form->bind($row);
            }
        }
        // POST有 更新処理
        else {
<?php if ($this->branch) : ?>

            // 所属 branch かのチェック
            if ($this->auth()->get('branch_no') != $this->params()->fromPost('branch_no')
                    && !$this->auth()->get('admin')) {
                $this->flashMessenger()->addMessage('許可されていません。');
                return $this->redirect()->toRoute('app', array(
                    'controller' => 'failed', 'action' => 'index'
                ));
            }
<?php endif; ?>

            // ToDo: 他にチェックが必要なら追加せよ

            $token_id = $this->container()->get('token_id');
            $this->container()->clear('token_id');
            $filter->setCreateToken($token_id);
            $filter->setInputFilter();
            $form->setInputFilter($filter->getInputFilter());
            $form->setData($request->getPost());

            $success = false;
            if ($form->isValid()) {
                // 挿入処理を実施
                $success = $db->insertRecord($this->auth()->get('user_no'), $form->getData());
            }
            else {
                // フィルター後の結果を form にセット
                $data = $form->getInputFilter()->getValues();
                $form->bind(get_array_object($data));
            }
            if ($success) {
                $this->flashMessenger()->addMessage("処理完了");
                return $this->redirect()->toRoute('app', array(
                    'controller' => '<?php echo $baseFolder ?>',
                    'action' => 'list',
                ));
            }
        }

        $token_id = make_token_id();
        $this->container()->set('token_id', $token_id);
        $form->get('token_id')->setAttribute('value', $token_id);
        $form->get('submit')->setAttribute('value', '登録');
        $form->get('reset')->setAttribute('value', 'リセット');
<?php if ($this->branch) : ?>

        // branch_no の初期値を登録ユーザと同一とする
        if (!$this->auth()->get('admin')) {
            $form->setData(array('branch_no' => $this->auth()->get('branch_no')));
        }
<?php endif; ?>

        $values = array(
            'id' => '',
            'action' => 'add',
            'form' => $form,
            'admin' => $this->auth()->get('admin'),
        );

        $view = new ViewModel($values);
        $view->setTemplate('/' . VIEW_DIR . '/<?php echo $baseFolder ?>/edit.phtml');
        return $view;
    }

    /**
     * 更新用編集画面 + 更新処理
     * @return ViewModel
     */
    public function editAction()
    {
        $this->init();
        $err_msg = '';

        // 指定id から編集対象・権限をチェック
        $id = (int) $this->params()->fromRoute('id', 0);
        if (!$id) {
            $success = false;
        }
        else {
            $success = (2 < $this->ctrlLv) ? true : false;
        }

        // 問題有 → エラーページへリダイレクト
        if (!$success) {
            return $this->redirect()->toRoute('app', array(
                'controller' => 'failed', 'action' => 'forbidden'
            ));
        }

        // ToDo : 必要な処理を実装せよ
        $form = new <?php echo $form; ?>();
        $form->setEditForm();
        $db = new <?php echo $entity; ?>();
        $filter = new <?php echo $filter; ?>();

        // DB より編集対象情報を取得
        $postRequest = $this->container()->get('postRequest');
        if ($postRequest) {
            $this->container()->clear('postRequest');
            $row = get_array_object(json_decode($postRequest, true));
        }
        else {
            $row = $db->db()->getFetchOne($id);
        }

        // 対象レコードが無い場合
        $success = false;

        if (!$row || $row->deleted) {
            $this->flashMessenger()->addMessage('指定レコードは存在しません。');
        }
<?php if ($this->branch) : ?>

        // 自社所属以外のレコード編集を原則禁止とする
        else if (!$this->auth()->get('admin')
                && $this->auth()->get('branch_no') != $row->branch_no) {
            $this->flashMessenger()->addMessage('許可されていません。');
        }
<?php endif; ?>

        else {
            $success = true;
        }

        if (!$success) {
            return $this->redirect()->toRoute('app', array(
                'controller' => 'failed', 'action' => 'index'
            ));
        }

        $request = $this->getRequest();

        // POST無 編集画面描画
        if (!$request->isPost()) {
            $form->bind($row);

            $beforeData = make_before_data($row, '<?php echo $this->pk; ?>');
            if ($beforeData) {
               $form->bind($beforeData);
            }
        }
        // POST有 更新処理
        else {
<?php if ($this->branch) : ?>

            // 所属 branch かのチェック
            if ($this->auth()->get('branch_no') != $this->params()->fromPost('branch_no')
                    && !$this->auth()->get('admin')) {
                $this->flashMessenger()->addMessage('許可されていません。');
                return $this->redirect()->toRoute('app', array(
                    'controller' => 'failed', 'action' => 'index'
                ));
            }
<?php endif; ?>

            // ToDo: 他にチェックが必要なら追加せよ

            $token_id = $this->container()->get('token_id');
            $this->container()->clear('token_id');
            $filter->setCreateToken($token_id);
            $form->setInputFilter($filter->getInputFilter());
            $form->setData($request->getPost());

            $success = $form->isValid();

            if ($success) {
                $success = check_change_data($request->getPost());
                $err_msg = $success ? '' : '変更を確認できません。';
            }

            if ($success) {
                // 更新処理を実施
                $success = $db->updateRecord($this->auth()->get('user_no'), $form->getData());
            }
            else {
                // フィルター後の結果を form にセット
                $data = $form->getInputFilter()->getValues();
                $form->bind(get_array_object($data));
            }

            if (false !== $success) {
                $this->flashMessenger()->addMessage("成功しました。");
                return $this->redirect()->toRoute('app', array(
                    'controller' => '<?php echo $baseFolder ?>',
                    'action' => 'list',
                ));
            }
        }

        $token_id = make_token_id();
        $this->container()->set('token_id', $token_id);

        $form->get('token_id')->setAttribute('value', $token_id);
        $form->get('submit')->setAttribute('value', '更新');
        $form->get('reset')->setAttribute('value', 'リセット');
<?php if ($this->branch) : ?>

        // branch_no の初期値を登録ユーザと同一とする
        if (!$this->auth()->get('admin')) {
            $form->setData(array('branch_no' => $this->auth()->get('branch_no')));
        }
<?php endif; ?>

        $values = array(
            'id' => $id,
            'action' => 'edit',
            'form' => $form,
            'admin' => $this->auth()->get('admin'),
            'err_msg' => $err_msg,
        );

        $view = new ViewModel($values);
        $view->setTemplate('/' . VIEW_DIR . '/<?php echo $baseFolder ?>/edit.phtml');
        return $view;
    }

    /**
     * 論理削除処理
     * @return ViewModel
     */
    public function deleteAction()
    {
        $this->init();

        $id = (int) $this->params()->fromRoute('id', 0);
        if (!$id) {
            $success = false;
        }
        else {
            $success = (4 == $this->ctrlLv) ? true : false;
        }
        $db = new <?php echo $entity; ?>;

<?php if ($this->branch) : ?>

        // 所属 branch のレコードかチェック
        if ($success && !$this->auth()->get('admin')) {
            $row = $db->db()->getFetchOne($id);
            $success = ($this->auth()->get('branch_no') == $row->branch_no);
        }
<?php endif; ?>

        // 問題無時に処理
        if ($success) {
            $success = $db->db()->logicalDelete($id, $this->auth()->get('user_no'));
        }

        $this->flashMessenger()
                ->addMessage($success ? '削除しました。' : '処理失敗');

        $view = new ViewModel(array(
            'message' => ($success ? 'success' : 'failed')));
        $view->setTemplate('/common/message.phtml');
        $view->setTerminal(true);
        return $view;
    }

    /**
     * 復帰処理
     * @return ViewModel
     */
    public function restoreAction()
    {
        $this->init();

        $id = (int) $this->params()->fromRoute('id', 0);
        if (!$id) {
            $success = false;
        }
        else {
            $success = (4 == $this->ctrlLv) ? true : false;
        }
        $db = new <?php echo $entity; ?>;

<?php if ($this->branch) : ?>

        // 所属 branch のレコードかチェック
        if ($success && !$this->auth()->get('admin')) {
            $row = $db->db()->getFetchOne($id);
            $success = ($this->auth()->get('branch_no') == $row->branch_no);
        }
<?php endif; ?>

        // 問題無時に処理
        if ($success) {
            $success = $db->db()->restoreRecord($id, $this->auth()->get('user_no'));
        }

        $this->flashMessenger()
                ->addMessage($success ? '復帰しました。' : '処理失敗');

        $view = new ViewModel(array(
            'message' => ($success ? 'success' : 'failed')));
        $view->setTemplate('/common/message.phtml');
        $view->setTerminal(true);
        return $view;
    }
}
