<?php
/**
 * Form Skelton
 * author : Aruze Gaming America, Inc.
 */

$baseFolder = $this->baseFolder;
$nameId = $this->nameId;
$form = $nameId . 'Form';

header("Content-type: application/octet-stream");
header("Content-Disposition: attachment; filename=\"{$form}.php\"");

echo '<?php'; ?>

/**
 * Zend Framework (http://framework.zend.com/)
 *
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2015 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace App\Form;
use Zend\Form\Form;

class <?php echo $form; ?> extends Form
{
    /**
     * 一覧 - 検索用フォーム
     * ToDo : 過不足は各自で対応せよ
     */
    public function setListForm()
    {
        parent::__construct('search-form');
        $this->setAttribute('method', 'get');
        $this->add(
            array(
                'name' => 'ord',
                'attributes' => array(
                    'type' => 'hidden',
                    'id' => 'ord',
                ),
            )
        );
<?php
    foreach ($this->col as $row) {
        $column = gv('Field', $row);
        if ($column == 'deleted' || $column == 'create_user'
                || $column == 'create_time' || $column == 'update_user'
                || $column == 'update_time' || gv('Key', $row) == 'PRI'
                || ($column != 'branch_no' && preg_match('/^(tinyint|smallint|mediumint|int|bigint)/', gv('Type', $row)))
                || $column == 'order_no'
                ) {
            continue;
        } ?>
        $this->add(
            array(
                'name' => '<?php echo 'search-' . $column ; ?>',
                'attributes' => array(
                    'type' => 'text',
                    'id' => '<?php echo 'search-' . $column ; ?>',
                ),
                'options' => array(
                    'label' => '<?php echo gv('Comment', $row); ?>',
                ),
            )
        );
<?php
    } ?>

        $this->add(
            array(
                'name' => 'submit',
                'attributes' => array(
                    'type' => 'submit',
                    'value' => '検索',
                    'id' => 'search-submit',
                    'class' => 'btn',
                    'onclick' => 'search();',
                ),
            )
        );
        $this->add(
            array(
                'name' => 'clear',
                'attributes' => array(
                    'type' => 'button',
                    'value' => 'CLR',
                    'id' => 'search-clear',
                    'class' => 'btn',
                ),
            )
        );
    }

    /**
     * 編集用フォーム
     * ToDo : 過不足は各自で対応せよ
     */
    public function setEditForm()
    {
        parent::__construct('<?php echo $baseFolder; ?>_edit');
        $this->setAttribute('method', 'post');

        $this->add(
            array(
                'name' => 'token_id',
                'attributes' => array(
                    'type' => 'hidden',
                    'id' => 'token_id',
                ),
            )
        );
        $this->add(
            array(
                'name' => '<?php echo $this->pk; ?>',
                'attributes' => array(
                    'type' => 'hidden',
                    'id' => '<?php echo $this->pk; ?>',
                ),
            )
        );
        $this->add(
            array(
                'name' => 'update_time',
                'attributes' => array(
                    'type' => 'hidden',
                    'id' => 'update_time',
                ),
            )
        );

<?php
    foreach ($this->col as $row) {
        $column = gv('Field', $row);
        if ($column == 'deleted' || $column == 'create_user'
                || $column == 'create_time' || $column == 'update_user'
                || $column == 'update_time' || gv('Key', $row) == 'PRI'
                || $column == 'order_no'
                ) {
            continue;
        } ?>

        $this->add(
            array(
                'name' => '<?php echo $column ; ?>',
                'attributes' => array(
                    'type' => '',
                    'id' => '<?php echo $column ; ?>',
                ),
                'options' => array(
                    'label' => '<?php echo gv('Comment', $row); ?>',
                ),
            )
        );
<?php
    } ?>

<?php
    foreach ($this->col as $row) {
        $column = gv('Field', $row);
        if ($column == 'deleted' || $column == 'create_user'
                || $column == 'create_time' || $column == 'update_user'
                || $column == 'update_time' || gv('Key', $row) == 'PRI'
                || $column == 'order_no'
                ) {
            continue;
        } ?>
        $this->add(
            array(
                'name' => '<?php echo 'before_' . $column ; ?>',
                'attributes' => array(
                    'type' => 'hidden',
                    'id' => '<?php echo 'before_' . $column ; ?>',
                ),
            )
        );
<?php
    } ?>

        $this->add(
            array(
                'name' => 'submit',
                'attributes' => array(
                    'type' => 'submit',
                    'value' => '登録',
                    'id' => 'submit',
                    'class' => 'btn',
                ),
            )
        );
        $this->add(
            array(
                'name' => 'reset',
                'attributes' => array(
                    'type' => 'reset',
                    'value' => 'リセット',
                    'id' => 'reset',
                    'class' => 'btn',
                ),
            )
        );
    }
}