<?php
/**
 * view - list > Skelton
 * author : Aruze Gaming America, Inc.
 */

$baseFolder = $this->baseFolder;
$name = str_replace(array('・マスタテーブル', '・マスタ'), "", gv('Comment', $this->tbl));

header("Content-type: application/octet-stream");
header("Content-Disposition: attachment; filename=\"list.phtml\"");

echo '<?php'; ?>

/**
 * <?php echo $name; ?> 一覧画面（PC）
 * author : Aruze Gaming America, Inc.
 */

$title = '<?php echo $name; ?> 一覧';
$this->headTitle($title);
$form = $this->form;

<?php if ($this->use_detail) : ?>

$this->headLink()
        ->prependStylesheet($this->basePath('js/jq/colorbox/colorbox.css'));
$this->headScript()
        ->prependFile($this->basePath('js/jq/colorbox/jquery.colorbox-min.js'));
echo $this->ViewButton()->getViewButtonJs();
<?php endif; ?>

echo $this->PageCtrl()->getNaviJs();
?>

<script type="text/javascript">
<!-- //
    function delete_btn(id) {
        if (progress) {
            return false;
        }
        progress = true;
        var url = '<?php echo '<?php'; ?>

        echo $this->url('app', array(
                    'controller' => '<?php echo $baseFolder; ?>',
                    'action' => 'delete',
                ));
        ?>/' + id;

        $.ajax({
            type: 'POST',
            url: url,
            success: function() {
                location.reload();
            }
        });
    }

    function restore_btn(id) {
        if (progress) {
            return false;
        }
        progress = true;
        var url = '<?php echo '<?php'; ?>

        echo $this->url('app', array(
                    'controller' => '<?php echo $baseFolder; ?>',
                    'action' => 'restore',
                ));
        ?>/' + id;

        $.ajax({
            type: 'POST',
            url: url,
            success: function() {
                location.reload();
            }
        });
    }
<?php if ($this->branch) : ?>

<?php echo '<?php'; ?> if(!$this->admin): ?>

    $(window).load(function() {
        $('#search-branch_no option').attr('disabled', true);
        $('#search-branch_no option:selected').attr('disabled', false);
    });
<?php echo '<?php'; ?> endif; ?>

<?php endif; ?>
// -->
</script>

<ul class="breadcrumb">
    <li><a href="<?php echo '<?php'; ?> echo BASE_URL; ?>">Top</a></li>
    <li><?php echo '<?php'; ?> echo $this->escapeHTML($this->translate($title)); ?></li>
</ul>

<div id="main">
    <div class="msg_box">
<?php echo '<?php'; ?>

    if ($this->message) :
        echo $this->escapeHTML($this->translate($this->message));
    endif;
 ?>
    </div>
    <br>

    <div class="right_box">
<?php echo '<?php'; ?>

    $jump = "";
    if (1 < $this->ctrlLv) :
        $jump = ' onclick="jump(\''
            . $this->url('app', array(
                'controller' => '<?php echo $baseFolder; ?>',
                'action' => 'add',
            ))
            . '\');"';
    endif;
?>
        <button type="button" class="ctrl<?php echo '<?php'; ?>

                echo !$jump ? ' disabled' : '';
                ?>"<?php echo '<?php'; ?>

                echo $jump; ?>><?php echo '<?php'; ?>

                echo $this->escapeHTML($this->translate('新規'));
            ?></button>
    </div>

    <!-- search_box -->
    <div class="search_box">
<?php echo '<?php'; ?>

        // ToDo : 検索機能の過不足・レイアウトは各自で対応せよ
        echo $this->form()->openTag($form) . "\n";
        echo $this->formHidden($form->get('ord')) . "\n";
?>

        <table class="search">
            <tbody>
<?php
    foreach ($this->col as $row) {
        $column = gv('Field', $row);
        if ($column == 'deleted' || $column == 'create_user'
                || $column == 'create_time' || $column == 'update_user'
                || $column == 'update_time' || gv('Key', $row) == 'PRI'
                || ($column != 'branch_no' && preg_match('/^(tinyint|smallint|mediumint|int|bigint)/', gv('Type', $row)))
                || $column == 'order_no'
                ) {
            continue;
        }
?>
                <tr>
                    <th><?php echo '<?php';
                        ?> echo $this->formLabel($form->get('<?php
                        echo 'search-' . $column; ?>')); ?></th>
                    <td><?php echo '<?php';
                        ?> echo $this->formElement($form->get('<?php
                        echo 'search-' . $column; ?>')); ?></td>
                </tr>
<?php
    } ?>
            </tbody>
        </table>
<?php echo '<?php'; ?>

    echo $this->formElement($form->get('submit')) . "\n";
    echo $this->formElement($form->get('clear')) . "\n";
    echo $this->form()->closeTag();
?>

    </div>
    <!-- search_box -->
    <br><br>

    <!-- list_box -->
    <div class="list_box">
        <table class="list">
            <caption>
                <?php echo '<?php'; ?> echo $this->PageCtrl()->getNavi($this->page); ?>
            </caption>
            <thead>
                <tr>
                    <th class="ctrl"><?php echo '<?php'; ?>

                        echo $this->escapeHTML($this->translate('編集')); ?></th>
<?php if ($this->use_detail) : ?>
                    <th class="ctrl"><?php echo '<?php'; ?>

                        echo $this->escapeHTML($this->translate('確認')); ?></th>
<?php endif; ?>

<?php
    foreach ($this->col as $row) {
        $column = gv('Field', $row);
        if ($column == 'deleted' || gv('Key', $row) == 'PRI'
                || $column == 'order_no'
        ) {
            continue;
        }

        switch ($column) {
            case 'create_user':
                $comment = '登録者';
                $class = 'user';
                break;
            case 'create_time':
                $comment = '登録日時';
                $class = 'date';
                break;
            case 'update_user':
                $comment = '最終更新者';
                $class = 'user';
                break;
            case 'update_time':
                $comment = '最終更新日時';
                $class = 'date';
                break;
            default :
                $comment = gv('Comment', $row);
                $class = '';
                break;
        }
?>
                    <th class="<?php echo $class; ?>"><?php echo '<?php'; ?>

                        echo $this->escapeHTML($this->translate('<?php
                            echo $comment; ?>'));
                        echo $this->PageCtrl()->getOrderLink('<?php
                            echo $column; ?>');
                        ?></th>
<?php
    } ?>

                    <th class="ctrl"><?php echo '<?php'; ?>

                        echo $this->escapeHTML($this->translate('削除')); ?></th>
                </tr>
            </thead>
            <tbody>
<?php echo '<?php'; ?>

    foreach ($this->rows as $row) {
?>
                <tr<?php echo '<?php'; ?> echo gv('deleted', $row) ? ' class="deleted"' : ''; ?>>
                    <td class="ctrl">
<?php echo '<?php'; ?>

    $jump = "";
    if (2 < $this->ctrlLv) :
        $jump = ' onclick="jump(\''
            . $this->url('app', array(
                'controller' => '<?php echo $baseFolder ?>',
                'action' => 'edit',
                'id' => gv('<?php echo $this->pk; ?>', $row)
            ))
            . '\');"';
    endif;
?>
                        <button type="button" class="ctrl" <?php echo '<?php'; ?>

                            echo $jump; ?><?php echo '<?php'; ?>

                            echo gv('deleted', $row) || !$jump ? ' disabled=disabled' : '';
                            ?>><?php echo '<?php'; ?>

                            echo $this->escapeHTML($this->translate('編集'));
                        ?></button>
                    </td>
<?php if ($this->use_detail) : ?>

                    <td class="ctrl">
<?php echo '<?php'; ?>

    $attr = array(
        'url' => $this->url('app', array(
            'controller' => '<?php echo $baseFolder; ?>',
            'action' => 'detail',
            'id' => gv('<?php echo $this->pk; ?>', $row),
        )),
        'value' => $this->escapeHTML($this->translate('確認')),
        'class' => 'ctrl',
        'height' => 500,
        'width' => 600,
    );
    echo $this->ViewButton()->printViewButton($attr) . "\n"; ?>
                    </td>
<?php
    endif;

    foreach ($this->col as $row) {
        $column = gv('Field', $row);
        if ($column == 'deleted' || gv('Key', $row) == 'PRI'
                || $column == 'order_no'
        ) {
            continue;
        }

        switch ($column) {
            case 'create_user':
            case 'update_user':
                $class = 'user';
                break;
            case 'create_time':
            case 'update_time':
                $class = 'date';
                break;
            default :
                $class = '';
                break;
        }
?>
                    <td class="<?php echo $class; ?>"><?php echo '<?php'; ?>

                        echo $this->escapeHTML(gv('<?php echo $column; ?>', $row)); ?></td>
<?php
    } ?>

                    <td class="ctrl">
                        <button type="button" onclick="<?php echo '<?php'; ?>

                            echo gv('deleted', $row) ? 'restore' : 'delete';
                            ?>_btn('<?php echo '<?php'; ?>

                            echo gv('<?php echo $this->pk; ?>', $row); ?>');" class="ctrl"<?php echo '<?php'; ?>

                            echo 4 > $this->ctrlLv ? ' disabled=disabled' : '';
                            ?>><?php echo '<?php'; ?>

                            echo $this->escapeHTML(
                                    $this->translate((gv('deleted', $row) ? '復帰' : '削除')));
                        ?></button>
                    </td>
                </tr>
<?php echo '<?php'; ?>

    }
?>

            </tbody>
        </table>
    </div>
    <!-- list_box -->

</div>
<br>
        <!-- pc/<?php echo $baseFolder ?>/list.phtml -->
