    <h1>Hello World!</h1>

	<div class="row">
        <div class="col-md-12">
           <div class="box box-info">
            <div class="box-header">
              <h1 class="box-title"><span class="fa fa-gear"></span> Marketing Roadmap </h1>
              <small> (list)  * Estimated: 
              <span class="text-yellow" title="yellow"><i class="fa fa-fw fa-square"></i></span> 
              Done: <span class="text-orange" title="orange"><i class="fa fa-fw fa-square"></i></span>
               <br/>
              </small>
     
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">

              <table class="table table-hover">
               <thead class="text-center">
                <tr>
                  <th colspan='11' style="text-align:center; background-color:#ECECEC;border-right:1px solid gainsboro">Product Status</th>
                  <th colspan='8' style="text-align:center;background-color:#ECECEC">Sales Promotions</th>
                </tr>
                </thead>
                
              <thead>
                <tr>
                  <th>Edit</th>
                  <th class="sorting_desc" tabindex="0" aria-controls="example1"  aria-label="Browser: activate to sort column ascending" aria-sort="descending" style="width: 360px;">Title</th>
                  <th>Market</th>
                  <th>Status</th>
                  <th>Platform</th>
                  <th>Category</th>
                  <th>Development Start</th>
                  <th>Development Finished</th>
                  <th>Submission</th>
                  <th>Regulator</th>
                  <th>Approval</th>
                  <th>Master Release</th>
                  <th>Lauching</th>
                  <th>Artwork Sales Promotions</th>
                  <th>GSlick</th>
                  <th>Demo Software</th>
                  <th>Movie</th>
                  <th>Artwork Training </th>
                  <th>Website</th>
                </tr>
                </thead>
       
                <tbody>
                <tr>
                  <td><a href="edit.html" title="Edit"><i class="fa fa-fw fa-pencil-square-o"></i></a>  <a href="view.html" title="view details"><i class="fa fa-fw fa-external-link"></i></a></td>
                  <td><span class="label bg-yellow">WILD DANCE FIRE</span></td>
                  <td>GLI</td>
                  <td>Under Development</td>
                  <td>9/15/2015</td>
                  <td>9/16/2015</td>
                   <td>9/17/2015</td>
                  <td>7/1/2015</td>
                  <td>7/10/2015</td>
                  <td> - </td>
                  <td>8/6/2015</td>
                  <td> - </td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                </tr>
                <tr>
                  <td><a href="edit.html" title="Edit"><i class="fa fa-fw fa-pencil-square-o"></i></a>  <a href="view.html" title="view details"><i class="fa fa-fw fa-external-link"></i></a></td>
                  <td><span class="label bg-yellow">WILD DANCE FIRE</span></td>
                  <td>GLI</td>
                  <td>Under Development</td>
                  <td>9/15/2015</td>
                  <td>9/16/2015</td>
                   <td>9/17/2015</td>
                  <td>7/1/2015</td>
                  <td>7/10/2015</td>
                  <td> - </td>
                  <td>8/6/2015</td>
                  <td> - </td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                </tr>
                
                <tr>
                  <td><a href="edit.html" title="Edit"><i class="fa fa-fw fa-pencil-square-o"></i></a>  <a href="view.html" title="view details"><i class="fa fa-fw fa-external-link"></i></a></td>
                  <td><span class="label bg-yellow">WILD DANCE FIRE</span></td>
                  <td>GLI</td>
                  <td>Under Development</td>
                  <td>9/15/2015</td>
                  <td>9/16/2015</td>
                   <td>9/17/2015</td>
                  <td>7/1/2015</td>
                  <td>7/10/2015</td>
                  <td> - </td>
                  <td>8/6/2015</td>
                  <td> - </td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                </tr>
                
                <tr>
                  <td><a href="edit.html" title="Edit"><i class="fa fa-fw fa-pencil-square-o"></i></a>  <a href="view.html" title="view details"><i class="fa fa-fw fa-external-link"></i></a></td>
                  <td><span class="label bg-yellow">WILD DANCE FIRE</span></td>
                  <td>GLI</td>
                  <td>Under Development</td>
                  <td>9/15/2015</td>
                  <td>9/16/2015</td>
                   <td>9/17/2015</td>
                  <td>7/1/2015</td>
                  <td>7/10/2015</td>
                  <td> - </td>
                  <td>8/6/2015</td>
                  <td> - </td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                </tr>
                
                 <tr>
                  <td><a href="edit.html" title="Edit"><i class="fa fa-fw fa-pencil-square-o"></i></a>  <a href="view.html" title="view details"><i class="fa fa-fw fa-external-link"></i></a></td>
                  <td><span class="label bg-yellow">WILD DANCE FIRE</span></td>
                  <td>GLI</td>
                  <td>Under Development</td>
                  <td>9/15/2015</td>
                  <td>9/16/2015</td>
                   <td>9/17/2015</td>
                  <td>7/1/2015</td>
                  <td>7/10/2015</td>
                  <td> - </td>
                  <td>8/6/2015</td>
                  <td> - </td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                </tr>
                
                <tr>
                  <td><a href="edit.html" title="Edit"><i class="fa fa-fw fa-pencil-square-o"></i></a>  <a href="view.html" title="view details"><i class="fa fa-fw fa-external-link"></i></a></td>
                 <td><span class="label bg-orange">WILD DANCE FIRE</span></td>
                  <td>GLI</td>
                  <td>Under Development</td>
                  <td>9/15/2015</td>
                  <td>9/16/2015</td>
                   <td>9/17/2015</td>
                  <td>7/1/2015</td>
                  <td>7/10/2015</td>
                  <td> - </td>
                  <td>8/6/2015</td>
                  <td> - </td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                </tr>
                
                <tr>
                  <td><a href="edit.html" title="Edit"><i class="fa fa-fw fa-pencil-square-o"></i></a>  <a href="view.html" title="view details"><i class="fa fa-fw fa-external-link"></i></a></td>
                  <td><span class="label bg-orange">WILD DANCE FIRE</span></td>
                  <td>GLI</td>
                  <td>Under Development</td>
                  <td>9/15/2015</td>
                  <td>9/16/2015</td>
                   <td>9/17/2015</td>
                  <td>7/1/2015</td>
                  <td>7/10/2015</td>
                  <td> - </td>
                  <td>8/6/2015</td>
                  <td> - </td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                  <td>9/27/2015</td>
                </tr>
              </tbody></table>
              <div>
              </div>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
        <!-- /.col -->
      </div>
