<?php
/**
 * user bundle regist > section, position edit (PC)
 * author : Aruze Gaming America, Inc.
 */

$title = 'User Batch Registration';
//$title = 'ユーザ 一括登録';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('app', array(
        'controller' => 'work-user',
        'action' => 'batch-edit',
)));
$form->setAttribute('novalidate', 'novalidate');
?>

<ul class="breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>">Top</a></li>
<?php if (!$this->self) : ?>
    <li><span onclick="jump('<?php
            echo $this->url('app', array(
                    'controller' => 'work-user',
                    'action' => 'list',
                ));
            ?>');"><?php
                echo $this->escapeHTML($this->translate('List')); ?></span></li>
                <!--echo $this->escapeHTML($this->translate('一覧')); ?></span></li>-->
<?php endif; ?>
</ul>

<div id="main">
    <div class="err_msg"><?php
    if (isset($this->err_msg) && $this->err_msg) :
        echo "<br><br>";
        echo nl2br(
            $this->escapeHtml($this->translate($this->err_msg)), false);
    endif; ?></div>
    <br>

<?php
    echo $this->form()->openTag($form) . "\n";
    echo $this->formHidden($form->get('token_id')) . "\n";

    $error = $this->formElementerrors($form->get('token_id'));
    if ($error) :
        echo $error . "\n";
    endif;
?>

    <table class="edit">
        <tr>
            <th>
                <?php echo $this->formLabel($form->get('section_no')); ?>
                <span class="required">*</span>
            </th>
            <td>
                <?php echo $this->formElement($form->get('section_no')); ?><br>
                <?php echo $this->formElementerrors($form->get('section_no')); ?>
            </td>
        </tr>
        <tr>
            <th>
                <?php echo $this->formLabel($form->get('position_no')); ?>
                <span class="required">*</span>
            </th>
            <td>
                <?php echo $this->formElement($form->get('position_no')); ?><br>
                <?php echo $this->formElementerrors($form->get('position_no')); ?>
            </td>
        </tr>
        <tr>
            <th><?php
                    echo $this->escapeHTML($this->translate('User')); ?></th>
                    <!--echo $this->escapeHTML($this->translate('ユーザ')); ?></th>-->
            <td>
                <?php
                foreach ($this->row as $row) {
                    echo $this->escapeHTML(gv('user_name', $row)) . "<br>\n";
                }
                ?>

            </td>
        </tr>
    </table>

<?php
    echo $this->formSubmit($form->get('submit')) . "\n";
    echo $this->form()->closeTag();
?>

</div>
<br>

<script type="text/javascript">
<!-- //
    $(document).ready(function() {
        $('#submit').click(function() {
            if (progress) {
                return false;
            }
            else {
                progress = true;
                return $('#user_edit').submit();
            }
        });
    });
// -->
</script>

        <!-- pc/work-user/batch.phtml -->